"""Stable governance import surface for MiniGPT release evidence."""

from __future__ import annotations

from minigpt.governance.maturity import (
    CAPABILITY_SPECS,
    CapabilitySpec,
    build_maturity_narrative,
    build_maturity_summary,
    render_maturity_narrative_html,
    render_maturity_summary_html,
    write_maturity_narrative_outputs,
    write_maturity_summary_outputs,
)
from minigpt.governance.registry import (
    REGISTRY_ARTIFACT_PATHS,
    RegisteredRun,
    build_run_registry,
    discover_run_dirs,
    render_registry_html,
    summarize_registered_run,
    write_registry_outputs,
)
from minigpt.governance.release import (
    DEFAULT_COMPARISON_PROFILES,
    DEFAULT_RELEASE_GATE_POLICY_PROFILE,
    RELEASE_GATE_POLICY_PROFILES,
    build_release_bundle,
    build_release_gate,
    build_release_gate_profile_comparison,
    build_release_readiness_comparison,
    build_release_readiness_dashboard,
    check_release_readiness_drift_contract,
    exit_code_for_gate,
    release_gate_policy_profiles,
    render_release_bundle_html,
    render_release_gate_html,
    render_release_readiness_comparison_html,
    render_release_readiness_html,
    resolve_release_gate_policy,
    resolve_release_readiness_comparison_path,
    write_release_bundle_outputs,
    write_release_gate_outputs,
    write_release_readiness_comparison_outputs,
    write_release_readiness_drift_contract_outputs,
    write_release_readiness_outputs,
)

__all__ = [
    "build_release_bundle",
    "render_release_bundle_html",
    "write_release_bundle_outputs",
    "DEFAULT_RELEASE_GATE_POLICY_PROFILE",
    "RELEASE_GATE_POLICY_PROFILES",
    "release_gate_policy_profiles",
    "resolve_release_gate_policy",
    "build_release_gate",
    "exit_code_for_gate",
    "render_release_gate_html",
    "write_release_gate_outputs",
    "DEFAULT_COMPARISON_PROFILES",
    "build_release_gate_profile_comparison",
    "build_release_readiness_dashboard",
    "render_release_readiness_html",
    "write_release_readiness_outputs",
    "build_release_readiness_comparison",
    "render_release_readiness_comparison_html",
    "write_release_readiness_comparison_outputs",
    "resolve_release_readiness_comparison_path",
    "check_release_readiness_drift_contract",
    "write_release_readiness_drift_contract_outputs",
    "CapabilitySpec",
    "CAPABILITY_SPECS",
    "build_maturity_summary",
    "render_maturity_summary_html",
    "write_maturity_summary_outputs",
    "build_maturity_narrative",
    "render_maturity_narrative_html",
    "write_maturity_narrative_outputs",
    "REGISTRY_ARTIFACT_PATHS",
    "RegisteredRun",
    "build_run_registry",
    "discover_run_dirs",
    "summarize_registered_run",
    "render_registry_html",
    "write_registry_outputs",
]
