"""Compatibility exports for release governance reports and gates."""

from __future__ import annotations

from minigpt.release_bundle import (
    build_release_bundle,
    render_release_bundle_html,
    render_release_bundle_markdown,
    write_release_bundle_html,
    write_release_bundle_json,
    write_release_bundle_markdown,
    write_release_bundle_outputs,
)
from minigpt.release_gate import (
    build_release_gate,
    exit_code_for_gate,
    render_release_gate_html,
    render_release_gate_markdown,
    write_release_gate_html,
    write_release_gate_json,
    write_release_gate_markdown,
    write_release_gate_outputs,
)
from minigpt.release_gate_policy import (
    DEFAULT_RELEASE_GATE_POLICY_PROFILE,
    RELEASE_GATE_POLICY_PROFILES,
    release_gate_policy_profiles,
    resolve_release_gate_policy,
)
from minigpt.release_gate_comparison import (
    DEFAULT_COMPARISON_PROFILES,
    build_release_gate_profile_comparison,
    render_release_gate_profile_comparison_html,
    render_release_gate_profile_comparison_markdown,
    write_release_gate_profile_comparison_csv,
    write_release_gate_profile_comparison_html,
    write_release_gate_profile_comparison_json,
    write_release_gate_profile_comparison_markdown,
    write_release_gate_profile_comparison_outputs,
    write_release_gate_profile_delta_csv,
)
from minigpt.release_readiness import (
    build_release_readiness_dashboard,
    render_release_readiness_html,
    render_release_readiness_markdown,
    write_release_readiness_html,
    write_release_readiness_json,
    write_release_readiness_markdown,
    write_release_readiness_outputs,
)
from minigpt.release_readiness_comparison import (
    build_release_readiness_comparison,
    render_release_readiness_comparison_html,
    render_release_readiness_comparison_markdown,
    status_delta_label,
    write_release_readiness_comparison_csv,
    write_release_readiness_comparison_html,
    write_release_readiness_comparison_json,
    write_release_readiness_comparison_markdown,
    write_release_readiness_comparison_outputs,
    write_release_readiness_delta_csv,
)
from minigpt.release_readiness_drift_contract import (
    check_release_readiness_drift_contract,
    load_release_readiness_comparison,
    render_release_readiness_drift_contract_check,
    resolve_release_readiness_comparison_path,
    write_release_readiness_drift_contract_outputs,
)

__all__ = [
    "build_release_bundle",
    "render_release_bundle_html",
    "render_release_bundle_markdown",
    "write_release_bundle_html",
    "write_release_bundle_json",
    "write_release_bundle_markdown",
    "write_release_bundle_outputs",
    "DEFAULT_RELEASE_GATE_POLICY_PROFILE",
    "RELEASE_GATE_POLICY_PROFILES",
    "release_gate_policy_profiles",
    "resolve_release_gate_policy",
    "build_release_gate",
    "exit_code_for_gate",
    "render_release_gate_html",
    "render_release_gate_markdown",
    "write_release_gate_html",
    "write_release_gate_json",
    "write_release_gate_markdown",
    "write_release_gate_outputs",
    "DEFAULT_COMPARISON_PROFILES",
    "build_release_gate_profile_comparison",
    "render_release_gate_profile_comparison_html",
    "render_release_gate_profile_comparison_markdown",
    "write_release_gate_profile_comparison_csv",
    "write_release_gate_profile_comparison_html",
    "write_release_gate_profile_comparison_json",
    "write_release_gate_profile_comparison_markdown",
    "write_release_gate_profile_comparison_outputs",
    "write_release_gate_profile_delta_csv",
    "build_release_readiness_dashboard",
    "render_release_readiness_html",
    "render_release_readiness_markdown",
    "write_release_readiness_html",
    "write_release_readiness_json",
    "write_release_readiness_markdown",
    "write_release_readiness_outputs",
    "build_release_readiness_comparison",
    "render_release_readiness_comparison_html",
    "render_release_readiness_comparison_markdown",
    "status_delta_label",
    "write_release_readiness_comparison_csv",
    "write_release_readiness_comparison_html",
    "write_release_readiness_comparison_json",
    "write_release_readiness_comparison_markdown",
    "write_release_readiness_comparison_outputs",
    "write_release_readiness_delta_csv",
    "resolve_release_readiness_comparison_path",
    "load_release_readiness_comparison",
    "check_release_readiness_drift_contract",
    "render_release_readiness_drift_contract_check",
    "write_release_readiness_drift_contract_outputs",
]
