"""MiniGPT learning project."""

from __future__ import annotations

from importlib import import_module
from typing import Any

__all__ = [
    "GPTConfig",
    "MiniGPT",
    "CharTokenizer",
    "BPETokenizer",
    "load_tokenizer",
    "TrainingRecord",
    "TokenPrediction",
    "ChatTurn",
    "PreparedChatPrompt",
    "build_chat_prompt",
    "RunComparison",
    "build_comparison_report",
    "render_comparison_html",
    "render_comparison_markdown",
    "DashboardArtifact",
    "PreparedDataset",
    "SourceFileSummary",
    "build_prepared_dataset",
    "write_prepared_dataset",
    "build_dataset_version_manifest",
    "build_dataset_quality_report",
    "write_dataset_quality_json",
    "PromptCase",
    "PromptSuite",
    "build_eval_suite_report",
    "load_prompt_suite",
    "RegisteredRun",
    "build_run_registry",
    "render_registry_html",
    "write_registry_html",
    "build_run_manifest",
    "write_run_manifest_json",
    "build_dashboard_payload",
    "write_dashboard",
    "ParameterGroup",
    "build_model_report",
    "PlaygroundLink",
    "build_playground_payload",
    "write_playground",
    "SamplingCase",
    "SamplingResult",
    "default_sampling_cases",
    "CheckpointOption",
    "InferenceSafetyProfile",
    "GenerationRequest",
    "GenerationPairRequest",
    "GenerationResponse",
    "build_checkpoint_compare_payload",
    "build_checkpoints_payload",
    "build_health_payload",
    "build_model_info_payload",
    "discover_checkpoint_options",
    "parse_generation_request",
    "parse_generation_pair_request",
    "build_pair_batch_case_result",
    "build_pair_batch_report",
    "build_pair_batch_trend_report",
    "write_pair_batch_outputs",
    "write_pair_batch_trend_outputs",
    "render_pair_generation_html",
    "write_pair_generation_artifacts",
    "build_maintenance_batching_report",
    "build_maintenance_proposal_decision",
    "write_maintenance_batching_outputs",
    "build_module_pressure_report",
    "write_module_pressure_outputs",
    "build_source_encoding_report",
    "render_source_encoding_html",
    "render_source_encoding_markdown",
    "write_source_encoding_csv",
    "write_source_encoding_html",
    "write_source_encoding_json",
    "write_source_encoding_markdown",
    "write_source_encoding_outputs",
    "build_ci_workflow_hygiene_report",
    "render_ci_workflow_hygiene_html",
    "render_ci_workflow_hygiene_markdown",
    "write_ci_workflow_hygiene_csv",
    "write_ci_workflow_hygiene_html",
    "write_ci_workflow_hygiene_json",
    "write_ci_workflow_hygiene_markdown",
    "write_ci_workflow_hygiene_outputs",
    "build_benchmark_scorecard_decision",
    "write_benchmark_scorecard_decision_outputs",
]

_EXPORTS = {
    "GPTConfig": ("model", "GPTConfig"),
    "MiniGPT": ("model", "MiniGPT"),
    "CharTokenizer": ("tokenizer", "CharTokenizer"),
    "BPETokenizer": ("tokenizer", "BPETokenizer"),
    "load_tokenizer": ("tokenizer", "load_tokenizer"),
    "TrainingRecord": ("history", "TrainingRecord"),
    "TokenPrediction": ("prediction", "TokenPrediction"),
    "ChatTurn": ("chat", "ChatTurn"),
    "PreparedChatPrompt": ("chat", "PreparedChatPrompt"),
    "build_chat_prompt": ("chat", "build_chat_prompt"),
    "RunComparison": ("comparison", "RunComparison"),
    "build_comparison_report": ("comparison", "build_comparison_report"),
    "render_comparison_html": ("comparison", "render_comparison_html"),
    "render_comparison_markdown": ("comparison", "render_comparison_markdown"),
    "DashboardArtifact": ("dashboard", "DashboardArtifact"),
    "PreparedDataset": ("data_prep", "PreparedDataset"),
    "SourceFileSummary": ("data_prep", "SourceFileSummary"),
    "build_prepared_dataset": ("data_prep", "build_prepared_dataset"),
    "write_prepared_dataset": ("data_prep", "write_prepared_dataset"),
    "build_dataset_version_manifest": ("data_prep", "build_dataset_version_manifest"),
    "build_dataset_quality_report": ("data_quality", "build_dataset_quality_report"),
    "write_dataset_quality_json": ("data_quality", "write_dataset_quality_json"),
    "PromptCase": ("eval_suite", "PromptCase"),
    "PromptSuite": ("eval_suite", "PromptSuite"),
    "build_eval_suite_report": ("eval_suite", "build_eval_suite_report"),
    "load_prompt_suite": ("eval_suite", "load_prompt_suite"),
    "RegisteredRun": ("registry", "RegisteredRun"),
    "build_run_registry": ("registry", "build_run_registry"),
    "render_registry_html": ("registry", "render_registry_html"),
    "write_registry_html": ("registry", "write_registry_html"),
    "build_run_manifest": ("manifest", "build_run_manifest"),
    "write_run_manifest_json": ("manifest", "write_run_manifest_json"),
    "build_dashboard_payload": ("dashboard", "build_dashboard_payload"),
    "write_dashboard": ("dashboard", "write_dashboard"),
    "ParameterGroup": ("model_report", "ParameterGroup"),
    "build_model_report": ("model_report", "build_model_report"),
    "PlaygroundLink": ("playground", "PlaygroundLink"),
    "build_playground_payload": ("playground", "build_playground_payload"),
    "write_playground": ("playground", "write_playground"),
    "SamplingCase": ("sampling", "SamplingCase"),
    "SamplingResult": ("sampling", "SamplingResult"),
    "default_sampling_cases": ("sampling", "default_sampling_cases"),
    "CheckpointOption": ("server", "CheckpointOption"),
    "InferenceSafetyProfile": ("server", "InferenceSafetyProfile"),
    "GenerationRequest": ("server", "GenerationRequest"),
    "GenerationPairRequest": ("server", "GenerationPairRequest"),
    "GenerationResponse": ("server", "GenerationResponse"),
    "build_checkpoint_compare_payload": ("server", "build_checkpoint_compare_payload"),
    "build_checkpoints_payload": ("server", "build_checkpoints_payload"),
    "build_health_payload": ("server", "build_health_payload"),
    "build_model_info_payload": ("server", "build_model_info_payload"),
    "discover_checkpoint_options": ("server", "discover_checkpoint_options"),
    "parse_generation_request": ("server", "parse_generation_request"),
    "parse_generation_pair_request": ("server", "parse_generation_pair_request"),
    "build_pair_batch_case_result": ("pair_batch", "build_pair_batch_case_result"),
    "build_pair_batch_report": ("pair_batch", "build_pair_batch_report"),
    "build_pair_batch_trend_report": ("pair_trend", "build_pair_batch_trend_report"),
    "write_pair_batch_outputs": ("pair_batch", "write_pair_batch_outputs"),
    "write_pair_batch_trend_outputs": ("pair_trend", "write_pair_batch_trend_outputs"),
    "render_pair_generation_html": ("server", "render_pair_generation_html"),
    "write_pair_generation_artifacts": ("server", "write_pair_generation_artifacts"),
    "build_maintenance_batching_report": ("maintenance_policy", "build_maintenance_batching_report"),
    "build_maintenance_proposal_decision": ("maintenance_policy", "build_maintenance_proposal_decision"),
    "write_maintenance_batching_outputs": ("maintenance_policy", "write_maintenance_batching_outputs"),
    "build_module_pressure_report": ("maintenance_policy", "build_module_pressure_report"),
    "write_module_pressure_outputs": ("maintenance_policy", "write_module_pressure_outputs"),
    "build_source_encoding_report": ("source_encoding_hygiene", "build_source_encoding_report"),
    "render_source_encoding_html": ("source_encoding_hygiene", "render_source_encoding_html"),
    "render_source_encoding_markdown": ("source_encoding_hygiene", "render_source_encoding_markdown"),
    "write_source_encoding_csv": ("source_encoding_hygiene", "write_source_encoding_csv"),
    "write_source_encoding_html": ("source_encoding_hygiene", "write_source_encoding_html"),
    "write_source_encoding_json": ("source_encoding_hygiene", "write_source_encoding_json"),
    "write_source_encoding_markdown": ("source_encoding_hygiene", "write_source_encoding_markdown"),
    "write_source_encoding_outputs": ("source_encoding_hygiene", "write_source_encoding_outputs"),
    "build_ci_workflow_hygiene_report": ("ci_workflow_hygiene", "build_ci_workflow_hygiene_report"),
    "render_ci_workflow_hygiene_html": ("ci_workflow_hygiene", "render_ci_workflow_hygiene_html"),
    "render_ci_workflow_hygiene_markdown": ("ci_workflow_hygiene", "render_ci_workflow_hygiene_markdown"),
    "write_ci_workflow_hygiene_csv": ("ci_workflow_hygiene", "write_ci_workflow_hygiene_csv"),
    "write_ci_workflow_hygiene_html": ("ci_workflow_hygiene", "write_ci_workflow_hygiene_html"),
    "write_ci_workflow_hygiene_json": ("ci_workflow_hygiene", "write_ci_workflow_hygiene_json"),
    "write_ci_workflow_hygiene_markdown": ("ci_workflow_hygiene", "write_ci_workflow_hygiene_markdown"),
    "write_ci_workflow_hygiene_outputs": ("ci_workflow_hygiene", "write_ci_workflow_hygiene_outputs"),
    "build_benchmark_scorecard_decision": ("benchmark_scorecard_decision", "build_benchmark_scorecard_decision"),
    "write_benchmark_scorecard_decision_outputs": ("benchmark_scorecard_decision", "write_benchmark_scorecard_decision_outputs"),
}


def __getattr__(name: str) -> Any:
    if name not in _EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr_name = _EXPORTS[name]
    value = getattr(import_module(f"{__name__}.{module_name}"), attr_name)
    globals()[name] = value
    return value
