"""MiniGPT learning project."""

from __future__ import annotations

from importlib import import_module
from typing import Any

__all__ = [
    "GPTConfig",
    "MiniGPT",
    "CharTokenizer",
    "BPETokenizer",
    "load_tokenizer",
    "TrainingRecord",
    "TokenPrediction",
    "ChatTurn",
    "PreparedChatPrompt",
    "build_chat_prompt",
    "RunComparison",
    "build_comparison_report",
    "render_comparison_html",
    "render_comparison_markdown",
    "DashboardArtifact",
    "PreparedDataset",
    "SourceFileSummary",
    "build_prepared_dataset",
    "write_prepared_dataset",
    "build_dataset_version_manifest",
    "DatasetVersionSummary",
    "build_dataset_version_comparison",
    "render_dataset_version_comparison_html",
    "render_dataset_version_comparison_markdown",
    "write_dataset_version_comparison_outputs",
    "build_dataset_quality_report",
    "write_dataset_quality_json",
    "PromptCase",
    "PromptSuite",
    "build_eval_suite_report",
    "summarize_prompt_suite_design",
    "load_builtin_prompt_suite",
    "load_prompt_suite",
    "standard_zh_prompt_suite",
    "RegisteredRun",
    "build_run_registry",
    "render_registry_html",
    "write_registry_html",
    "build_run_manifest",
    "write_run_manifest_json",
    "build_dashboard_payload",
    "write_dashboard",
    "ParameterGroup",
    "build_model_report",
    "PlaygroundLink",
    "build_playground_payload",
    "write_playground",
    "SamplingCase",
    "SamplingResult",
    "default_sampling_cases",
    "CheckpointOption",
    "InferenceSafetyProfile",
    "GenerationRequest",
    "GenerationPairRequest",
    "GenerationResponse",
    "build_checkpoint_compare_payload",
    "build_checkpoints_payload",
    "build_health_payload",
    "build_model_info_payload",
    "discover_checkpoint_options",
    "parse_generation_request",
    "parse_generation_pair_request",
    "build_pair_batch_case_result",
    "build_pair_batch_report",
    "build_pair_batch_trend_report",
    "write_pair_batch_outputs",
    "write_pair_batch_trend_outputs",
    "render_pair_generation_html",
    "write_pair_generation_artifacts",
    "build_maintenance_batching_report",
    "build_maintenance_proposal_decision",
    "write_maintenance_batching_outputs",
    "build_module_pressure_report",
    "write_module_pressure_outputs",
    "build_source_encoding_report",
    "render_source_encoding_html",
    "render_source_encoding_markdown",
    "write_source_encoding_csv",
    "write_source_encoding_html",
    "write_source_encoding_json",
    "write_source_encoding_markdown",
    "write_source_encoding_outputs",
    "build_ci_workflow_hygiene_report",
    "render_ci_workflow_hygiene_html",
    "render_ci_workflow_hygiene_markdown",
    "write_ci_workflow_hygiene_csv",
    "write_ci_workflow_hygiene_html",
    "write_ci_workflow_hygiene_json",
    "write_ci_workflow_hygiene_markdown",
    "write_ci_workflow_hygiene_outputs",
    "build_benchmark_scorecard_decision",
    "write_benchmark_scorecard_decision_outputs",
    "build_benchmark_history",
    "write_benchmark_history_outputs",
    "build_model_capability_route_promotion_history",
    "write_model_capability_route_promotion_history_outputs",
    "build_model_capability_route_promotion_portfolio",
    "write_model_capability_route_promotion_portfolio_outputs",
    "build_model_capability_route_promotion_regression_monitor",
    "write_model_capability_route_promotion_regression_monitor_outputs",
    "build_model_capability_route_promotion_gate",
    "write_model_capability_route_promotion_gate_outputs",
    "build_model_capability_route_promotion_release_packet",
    "write_model_capability_route_promotion_release_packet_outputs",
    "build_model_capability_route_promotion_release_packet_review",
    "write_model_capability_route_promotion_release_packet_review_outputs",
    "build_randomized_holdout_candidate_promotion_packet",
    "write_randomized_holdout_candidate_promotion_packet_outputs",
    "build_randomized_holdout_candidate_promotion_packet_review",
    "write_randomized_holdout_candidate_promotion_packet_review_outputs",
    "build_randomized_holdout_bounded_promotion_gate",
    "write_randomized_holdout_bounded_promotion_gate_outputs",
    "build_randomized_holdout_bounded_promotion_decision",
    "write_randomized_holdout_bounded_promotion_decision_outputs",
    "build_randomized_holdout_decision_index",
    "write_randomized_holdout_decision_index_outputs",
    "build_randomized_holdout_acceptance_summary",
    "write_randomized_holdout_acceptance_summary_outputs",
    "build_randomized_holdout_acceptance_summary_check",
    "write_randomized_holdout_acceptance_summary_check_outputs",
    "build_randomized_holdout_acceptance_publication_packet",
    "write_randomized_holdout_acceptance_publication_packet_outputs",
    "build_randomized_holdout_acceptance_publication_packet_review",
    "write_randomized_holdout_acceptance_publication_packet_review_outputs",
    "build_randomized_holdout_publication_decision",
    "write_randomized_holdout_publication_decision_outputs",
    "build_randomized_holdout_publication_decision_index",
    "write_randomized_holdout_publication_decision_index_outputs",
    "build_randomized_holdout_publication_registry_entry",
    "write_randomized_holdout_publication_registry_entry_outputs",
    "build_randomized_holdout_publication_registry_entry_check",
    "write_randomized_holdout_publication_registry_entry_check_outputs",
    "build_randomized_holdout_publication_registry_packet",
    "write_randomized_holdout_publication_registry_packet_outputs",
    "build_randomized_holdout_publication_registry_manifest",
    "write_randomized_holdout_publication_registry_manifest_outputs",
    "build_randomized_holdout_publication_registry_manifest_review",
    "write_randomized_holdout_publication_registry_manifest_review_outputs",
    "build_randomized_holdout_publication_registry_lookup_packet",
    "write_randomized_holdout_publication_registry_lookup_packet_outputs",
    "build_randomized_holdout_publication_registry_lookup_packet_check",
    "write_randomized_holdout_publication_registry_lookup_packet_check_outputs",
    "build_randomized_holdout_publication_registry_lookup_index",
    "write_randomized_holdout_publication_registry_lookup_index_outputs",
    "build_randomized_holdout_publication_registry_lookup_index_review",
    "write_randomized_holdout_publication_registry_lookup_index_review_outputs",
    "build_randomized_holdout_publication_registry_downstream_guard",
    "write_randomized_holdout_publication_registry_downstream_guard_outputs",
    "build_randomized_holdout_publication_registry_downstream_receipt",
    "write_randomized_holdout_publication_registry_downstream_receipt_outputs",
    "build_randomized_holdout_publication_registry_downstream_receipt_review",
    "write_randomized_holdout_publication_registry_downstream_receipt_review_outputs",
    "build_randomized_holdout_publication_registry_downstream_consumer_packet",
    "write_randomized_holdout_publication_registry_downstream_consumer_packet_outputs",
    "build_randomized_holdout_publication_registry_downstream_consumer_packet_check",
    "write_randomized_holdout_publication_registry_downstream_consumer_packet_check_outputs",
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_review",
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_review_outputs",
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet",
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_outputs",
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_check",
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_check_outputs",
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index",
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_outputs",
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_review",
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_review_outputs",
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication",
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_outputs",
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_check",
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_check_outputs",
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_index",
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_index_outputs",
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_index_review",
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_index_review_outputs",
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt",
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_outputs",
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_review",
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_review_outputs",
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet",
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_outputs",
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_check",
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_check_outputs",
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_index",
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_index_outputs",
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_index_review",
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_index_review_outputs",
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt",
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt_outputs",
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt_review",
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt_review_outputs",
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt_packet",
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt_packet_outputs",
    "build_model_capability_route_promotion_review_decision",
    "write_model_capability_route_promotion_review_decision_outputs",
    "build_model_capability_route_promotion_decision_index",
    "write_model_capability_route_promotion_decision_index_outputs",
    "build_model_capability_route_promotion_decision_index_check",
    "write_model_capability_route_promotion_decision_index_check_outputs",
    "build_model_capability_route_promotion_governance_snapshot",
    "write_model_capability_route_promotion_governance_snapshot_outputs",
    "build_model_capability_route_promotion_downstream_guard",
    "write_model_capability_route_promotion_downstream_guard_outputs",
    "build_model_capability_route_promotion_consumer_plan",
    "write_model_capability_route_promotion_consumer_plan_outputs",
    "build_model_capability_route_promotion_bounded_benchmark_suite",
    "write_model_capability_route_promotion_bounded_benchmark_suite_outputs",
    "build_model_capability_route_promotion_bounded_benchmark_suite_review",
    "write_model_capability_route_promotion_bounded_benchmark_suite_review_outputs",
    "build_model_capability_route_promotion_bounded_benchmark_dry_run",
    "write_model_capability_route_promotion_bounded_benchmark_dry_run_outputs",
    "build_promoted_training_scale_seed_handoff_receipt_contract_summary",
    "write_promoted_training_scale_seed_handoff_receipt_contract_summary_outputs",
    "check_promoted_training_scale_seed_handoff_receipt_contract_summary",
    "write_promoted_training_scale_seed_handoff_receipt_contract_summary_check_outputs",
]

_EXPORTS = {
    "GPTConfig": ("model", "GPTConfig"),
    "MiniGPT": ("model", "MiniGPT"),
    "CharTokenizer": ("tokenizer", "CharTokenizer"),
    "BPETokenizer": ("tokenizer", "BPETokenizer"),
    "load_tokenizer": ("tokenizer", "load_tokenizer"),
    "TrainingRecord": ("history", "TrainingRecord"),
    "TokenPrediction": ("prediction", "TokenPrediction"),
    "ChatTurn": ("chat", "ChatTurn"),
    "PreparedChatPrompt": ("chat", "PreparedChatPrompt"),
    "build_chat_prompt": ("chat", "build_chat_prompt"),
    "RunComparison": ("comparison", "RunComparison"),
    "build_comparison_report": ("comparison", "build_comparison_report"),
    "render_comparison_html": ("comparison", "render_comparison_html"),
    "render_comparison_markdown": ("comparison", "render_comparison_markdown"),
    "DashboardArtifact": ("dashboard", "DashboardArtifact"),
    "PreparedDataset": ("data_prep", "PreparedDataset"),
    "SourceFileSummary": ("data_prep", "SourceFileSummary"),
    "build_prepared_dataset": ("data_prep", "build_prepared_dataset"),
    "write_prepared_dataset": ("data_prep", "write_prepared_dataset"),
    "build_dataset_version_manifest": ("data_prep", "build_dataset_version_manifest"),
    "DatasetVersionSummary": ("dataset_version_comparison", "DatasetVersionSummary"),
    "build_dataset_version_comparison": ("dataset_version_comparison", "build_dataset_version_comparison"),
    "render_dataset_version_comparison_html": ("dataset_version_comparison", "render_dataset_version_comparison_html"),
    "render_dataset_version_comparison_markdown": ("dataset_version_comparison", "render_dataset_version_comparison_markdown"),
    "write_dataset_version_comparison_outputs": ("dataset_version_comparison", "write_dataset_version_comparison_outputs"),
    "build_dataset_quality_report": ("data_quality", "build_dataset_quality_report"),
    "write_dataset_quality_json": ("data_quality", "write_dataset_quality_json"),
    "PromptCase": ("eval_suite", "PromptCase"),
    "PromptSuite": ("eval_suite", "PromptSuite"),
    "build_eval_suite_report": ("eval_suite", "build_eval_suite_report"),
    "summarize_prompt_suite_design": ("eval_suite_design", "summarize_prompt_suite_design"),
    "load_builtin_prompt_suite": ("eval_suite", "load_builtin_prompt_suite"),
    "load_prompt_suite": ("eval_suite", "load_prompt_suite"),
    "standard_zh_prompt_suite": ("eval_suites", "standard_zh_prompt_suite"),
    "RegisteredRun": ("registry", "RegisteredRun"),
    "build_run_registry": ("registry", "build_run_registry"),
    "render_registry_html": ("registry", "render_registry_html"),
    "write_registry_html": ("registry", "write_registry_html"),
    "build_run_manifest": ("manifest", "build_run_manifest"),
    "write_run_manifest_json": ("manifest", "write_run_manifest_json"),
    "build_dashboard_payload": ("dashboard", "build_dashboard_payload"),
    "write_dashboard": ("dashboard", "write_dashboard"),
    "ParameterGroup": ("model_report", "ParameterGroup"),
    "build_model_report": ("model_report", "build_model_report"),
    "PlaygroundLink": ("playground", "PlaygroundLink"),
    "build_playground_payload": ("playground", "build_playground_payload"),
    "write_playground": ("playground", "write_playground"),
    "SamplingCase": ("sampling", "SamplingCase"),
    "SamplingResult": ("sampling", "SamplingResult"),
    "default_sampling_cases": ("sampling", "default_sampling_cases"),
    "CheckpointOption": ("server", "CheckpointOption"),
    "InferenceSafetyProfile": ("server", "InferenceSafetyProfile"),
    "GenerationRequest": ("server", "GenerationRequest"),
    "GenerationPairRequest": ("server", "GenerationPairRequest"),
    "GenerationResponse": ("server", "GenerationResponse"),
    "build_checkpoint_compare_payload": ("server", "build_checkpoint_compare_payload"),
    "build_checkpoints_payload": ("server", "build_checkpoints_payload"),
    "build_health_payload": ("server", "build_health_payload"),
    "build_model_info_payload": ("server", "build_model_info_payload"),
    "discover_checkpoint_options": ("server", "discover_checkpoint_options"),
    "parse_generation_request": ("server", "parse_generation_request"),
    "parse_generation_pair_request": ("server", "parse_generation_pair_request"),
    "build_pair_batch_case_result": ("pair_batch", "build_pair_batch_case_result"),
    "build_pair_batch_report": ("pair_batch", "build_pair_batch_report"),
    "build_pair_batch_trend_report": ("pair_trend", "build_pair_batch_trend_report"),
    "write_pair_batch_outputs": ("pair_batch", "write_pair_batch_outputs"),
    "write_pair_batch_trend_outputs": ("pair_trend", "write_pair_batch_trend_outputs"),
    "render_pair_generation_html": ("server", "render_pair_generation_html"),
    "write_pair_generation_artifacts": ("server", "write_pair_generation_artifacts"),
    "build_maintenance_batching_report": ("maintenance_policy", "build_maintenance_batching_report"),
    "build_maintenance_proposal_decision": ("maintenance_policy", "build_maintenance_proposal_decision"),
    "write_maintenance_batching_outputs": ("maintenance_policy", "write_maintenance_batching_outputs"),
    "build_module_pressure_report": ("maintenance_policy", "build_module_pressure_report"),
    "write_module_pressure_outputs": ("maintenance_policy", "write_module_pressure_outputs"),
    "build_source_encoding_report": ("source_encoding_hygiene", "build_source_encoding_report"),
    "render_source_encoding_html": ("source_encoding_hygiene", "render_source_encoding_html"),
    "render_source_encoding_markdown": ("source_encoding_hygiene", "render_source_encoding_markdown"),
    "write_source_encoding_csv": ("source_encoding_hygiene", "write_source_encoding_csv"),
    "write_source_encoding_html": ("source_encoding_hygiene", "write_source_encoding_html"),
    "write_source_encoding_json": ("source_encoding_hygiene", "write_source_encoding_json"),
    "write_source_encoding_markdown": ("source_encoding_hygiene", "write_source_encoding_markdown"),
    "write_source_encoding_outputs": ("source_encoding_hygiene", "write_source_encoding_outputs"),
    "build_ci_workflow_hygiene_report": ("ci_workflow_hygiene", "build_ci_workflow_hygiene_report"),
    "render_ci_workflow_hygiene_html": ("ci_workflow_hygiene", "render_ci_workflow_hygiene_html"),
    "render_ci_workflow_hygiene_markdown": ("ci_workflow_hygiene", "render_ci_workflow_hygiene_markdown"),
    "write_ci_workflow_hygiene_csv": ("ci_workflow_hygiene", "write_ci_workflow_hygiene_csv"),
    "write_ci_workflow_hygiene_html": ("ci_workflow_hygiene", "write_ci_workflow_hygiene_html"),
    "write_ci_workflow_hygiene_json": ("ci_workflow_hygiene", "write_ci_workflow_hygiene_json"),
    "write_ci_workflow_hygiene_markdown": ("ci_workflow_hygiene", "write_ci_workflow_hygiene_markdown"),
    "write_ci_workflow_hygiene_outputs": ("ci_workflow_hygiene", "write_ci_workflow_hygiene_outputs"),
    "build_benchmark_scorecard_decision": ("benchmark_scorecard_decision", "build_benchmark_scorecard_decision"),
    "write_benchmark_scorecard_decision_outputs": ("benchmark_scorecard_decision", "write_benchmark_scorecard_decision_outputs"),
    "build_benchmark_history": ("benchmark_history", "build_benchmark_history"),
    "write_benchmark_history_outputs": ("benchmark_history", "write_benchmark_history_outputs"),
    "build_model_capability_route_promotion_history": (
        "model_capability_route_promotion_history",
        "build_model_capability_route_promotion_history",
    ),
    "write_model_capability_route_promotion_history_outputs": (
        "model_capability_route_promotion_history_artifacts",
        "write_model_capability_route_promotion_history_outputs",
    ),
    "build_model_capability_route_promotion_portfolio": (
        "model_capability_route_promotion_portfolio",
        "build_model_capability_route_promotion_portfolio",
    ),
    "write_model_capability_route_promotion_portfolio_outputs": (
        "model_capability_route_promotion_portfolio_artifacts",
        "write_model_capability_route_promotion_portfolio_outputs",
    ),
    "build_model_capability_route_promotion_regression_monitor": (
        "model_capability_route_promotion_regression_monitor",
        "build_model_capability_route_promotion_regression_monitor",
    ),
    "write_model_capability_route_promotion_regression_monitor_outputs": (
        "model_capability_route_promotion_regression_monitor_artifacts",
        "write_model_capability_route_promotion_regression_monitor_outputs",
    ),
    "build_model_capability_route_promotion_gate": (
        "model_capability_route_promotion_gate",
        "build_model_capability_route_promotion_gate",
    ),
    "write_model_capability_route_promotion_gate_outputs": (
        "model_capability_route_promotion_gate_artifacts",
        "write_model_capability_route_promotion_gate_outputs",
    ),
    "build_model_capability_route_promotion_release_packet": (
        "model_capability_route_promotion_release_packet",
        "build_model_capability_route_promotion_release_packet",
    ),
    "write_model_capability_route_promotion_release_packet_outputs": (
        "model_capability_route_promotion_release_packet_artifacts",
        "write_model_capability_route_promotion_release_packet_outputs",
    ),
    "build_model_capability_route_promotion_release_packet_review": (
        "model_capability_route_promotion_release_packet_review",
        "build_model_capability_route_promotion_release_packet_review",
    ),
    "write_model_capability_route_promotion_release_packet_review_outputs": (
        "model_capability_route_promotion_release_packet_review_artifacts",
        "write_model_capability_route_promotion_release_packet_review_outputs",
    ),
    "build_randomized_holdout_candidate_promotion_packet": (
        "randomized_holdout_candidate_promotion_packet",
        "build_randomized_holdout_candidate_promotion_packet",
    ),
    "write_randomized_holdout_candidate_promotion_packet_outputs": (
        "randomized_holdout_candidate_promotion_packet_artifacts",
        "write_randomized_holdout_candidate_promotion_packet_outputs",
    ),
    "build_randomized_holdout_candidate_promotion_packet_review": (
        "randomized_holdout_candidate_promotion_packet_review",
        "build_randomized_holdout_candidate_promotion_packet_review",
    ),
    "write_randomized_holdout_candidate_promotion_packet_review_outputs": (
        "randomized_holdout_candidate_promotion_packet_review_artifacts",
        "write_randomized_holdout_candidate_promotion_packet_review_outputs",
    ),
    "build_randomized_holdout_bounded_promotion_gate": (
        "randomized_holdout_bounded_promotion_gate",
        "build_randomized_holdout_bounded_promotion_gate",
    ),
    "write_randomized_holdout_bounded_promotion_gate_outputs": (
        "randomized_holdout_bounded_promotion_gate_artifacts",
        "write_randomized_holdout_bounded_promotion_gate_outputs",
    ),
    "build_randomized_holdout_bounded_promotion_decision": (
        "randomized_holdout_bounded_promotion_decision",
        "build_randomized_holdout_bounded_promotion_decision",
    ),
    "write_randomized_holdout_bounded_promotion_decision_outputs": (
        "randomized_holdout_bounded_promotion_decision_artifacts",
        "write_randomized_holdout_bounded_promotion_decision_outputs",
    ),
    "build_randomized_holdout_decision_index": (
        "randomized_holdout_decision_index",
        "build_randomized_holdout_decision_index",
    ),
    "write_randomized_holdout_decision_index_outputs": (
        "randomized_holdout_decision_index_artifacts",
        "write_randomized_holdout_decision_index_outputs",
    ),
    "build_randomized_holdout_acceptance_summary": (
        "randomized_holdout_acceptance_summary",
        "build_randomized_holdout_acceptance_summary",
    ),
    "write_randomized_holdout_acceptance_summary_outputs": (
        "randomized_holdout_acceptance_summary_artifacts",
        "write_randomized_holdout_acceptance_summary_outputs",
    ),
    "build_randomized_holdout_acceptance_summary_check": (
        "randomized_holdout_acceptance_summary_check",
        "build_randomized_holdout_acceptance_summary_check",
    ),
    "write_randomized_holdout_acceptance_summary_check_outputs": (
        "randomized_holdout_acceptance_summary_check_artifacts",
        "write_randomized_holdout_acceptance_summary_check_outputs",
    ),
    "build_randomized_holdout_acceptance_publication_packet": (
        "randomized_holdout_acceptance_publication_packet",
        "build_randomized_holdout_acceptance_publication_packet",
    ),
    "write_randomized_holdout_acceptance_publication_packet_outputs": (
        "randomized_holdout_acceptance_publication_packet_artifacts",
        "write_randomized_holdout_acceptance_publication_packet_outputs",
    ),
    "build_randomized_holdout_acceptance_publication_packet_review": (
        "randomized_holdout_acceptance_publication_packet_review",
        "build_randomized_holdout_acceptance_publication_packet_review",
    ),
    "write_randomized_holdout_acceptance_publication_packet_review_outputs": (
        "randomized_holdout_acceptance_publication_packet_review_artifacts",
        "write_randomized_holdout_acceptance_publication_packet_review_outputs",
    ),
    "build_randomized_holdout_publication_decision": (
        "randomized_holdout_publication_decision",
        "build_randomized_holdout_publication_decision",
    ),
    "write_randomized_holdout_publication_decision_outputs": (
        "randomized_holdout_publication_decision_artifacts",
        "write_randomized_holdout_publication_decision_outputs",
    ),
    "build_randomized_holdout_publication_decision_index": (
        "randomized_holdout_publication_decision_index",
        "build_randomized_holdout_publication_decision_index",
    ),
    "write_randomized_holdout_publication_decision_index_outputs": (
        "randomized_holdout_publication_decision_index_artifacts",
        "write_randomized_holdout_publication_decision_index_outputs",
    ),
    "build_randomized_holdout_publication_registry_entry": (
        "randomized_holdout_publication_registry_entry",
        "build_randomized_holdout_publication_registry_entry",
    ),
    "write_randomized_holdout_publication_registry_entry_outputs": (
        "randomized_holdout_publication_registry_entry_artifacts",
        "write_randomized_holdout_publication_registry_entry_outputs",
    ),
    "build_randomized_holdout_publication_registry_entry_check": (
        "randomized_holdout_publication_registry_entry_check",
        "build_randomized_holdout_publication_registry_entry_check",
    ),
    "write_randomized_holdout_publication_registry_entry_check_outputs": (
        "randomized_holdout_publication_registry_entry_check_artifacts",
        "write_randomized_holdout_publication_registry_entry_check_outputs",
    ),
    "build_randomized_holdout_publication_registry_packet": (
        "randomized_holdout_publication_registry_packet",
        "build_randomized_holdout_publication_registry_packet",
    ),
    "write_randomized_holdout_publication_registry_packet_outputs": (
        "randomized_holdout_publication_registry_packet_artifacts",
        "write_randomized_holdout_publication_registry_packet_outputs",
    ),
    "build_randomized_holdout_publication_registry_manifest": (
        "randomized_holdout_publication_registry_manifest",
        "build_randomized_holdout_publication_registry_manifest",
    ),
    "write_randomized_holdout_publication_registry_manifest_outputs": (
        "randomized_holdout_publication_registry_manifest_artifacts",
        "write_randomized_holdout_publication_registry_manifest_outputs",
    ),
    "build_randomized_holdout_publication_registry_manifest_review": (
        "randomized_holdout_publication_registry_manifest_review",
        "build_randomized_holdout_publication_registry_manifest_review",
    ),
    "write_randomized_holdout_publication_registry_manifest_review_outputs": (
        "randomized_holdout_publication_registry_manifest_review_artifacts",
        "write_randomized_holdout_publication_registry_manifest_review_outputs",
    ),
    "build_randomized_holdout_publication_registry_lookup_packet": (
        "randomized_holdout_publication_registry_lookup_packet",
        "build_randomized_holdout_publication_registry_lookup_packet",
    ),
    "write_randomized_holdout_publication_registry_lookup_packet_outputs": (
        "randomized_holdout_publication_registry_lookup_packet_artifacts",
        "write_randomized_holdout_publication_registry_lookup_packet_outputs",
    ),
    "build_randomized_holdout_publication_registry_lookup_packet_check": (
        "randomized_holdout_publication_registry_lookup_packet_check",
        "build_randomized_holdout_publication_registry_lookup_packet_check",
    ),
    "write_randomized_holdout_publication_registry_lookup_packet_check_outputs": (
        "randomized_holdout_publication_registry_lookup_packet_check_artifacts",
        "write_randomized_holdout_publication_registry_lookup_packet_check_outputs",
    ),
    "build_randomized_holdout_publication_registry_lookup_index": (
        "randomized_holdout_publication_registry_lookup_index",
        "build_randomized_holdout_publication_registry_lookup_index",
    ),
    "write_randomized_holdout_publication_registry_lookup_index_outputs": (
        "randomized_holdout_publication_registry_lookup_index_artifacts",
        "write_randomized_holdout_publication_registry_lookup_index_outputs",
    ),
    "build_randomized_holdout_publication_registry_lookup_index_review": (
        "randomized_holdout_publication_registry_lookup_index_review",
        "build_randomized_holdout_publication_registry_lookup_index_review",
    ),
    "write_randomized_holdout_publication_registry_lookup_index_review_outputs": (
        "randomized_holdout_publication_registry_lookup_index_review_artifacts",
        "write_randomized_holdout_publication_registry_lookup_index_review_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_guard": (
        "randomized_holdout_publication_registry_downstream_guard",
        "build_randomized_holdout_publication_registry_downstream_guard",
    ),
    "write_randomized_holdout_publication_registry_downstream_guard_outputs": (
        "randomized_holdout_publication_registry_downstream_guard_artifacts",
        "write_randomized_holdout_publication_registry_downstream_guard_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_receipt": (
        "randomized_holdout_publication_registry_downstream_receipt",
        "build_randomized_holdout_publication_registry_downstream_receipt",
    ),
    "write_randomized_holdout_publication_registry_downstream_receipt_outputs": (
        "randomized_holdout_publication_registry_downstream_receipt_artifacts",
        "write_randomized_holdout_publication_registry_downstream_receipt_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_receipt_review": (
        "randomized_holdout_publication_registry_downstream_receipt_review",
        "build_randomized_holdout_publication_registry_downstream_receipt_review",
    ),
    "write_randomized_holdout_publication_registry_downstream_receipt_review_outputs": (
        "randomized_holdout_publication_registry_downstream_receipt_review_artifacts",
        "write_randomized_holdout_publication_registry_downstream_receipt_review_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_packet": (
        "randomized_holdout_publication_registry_downstream_consumer_packet",
        "build_randomized_holdout_publication_registry_downstream_consumer_packet",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_packet_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_packet_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_packet_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_packet_check": (
        "randomized_holdout_publication_registry_downstream_consumer_packet_check",
        "build_randomized_holdout_publication_registry_downstream_consumer_packet_check",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_packet_check_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_packet_check_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_packet_check_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_index": (
        "randomized_holdout_publication_registry_downstream_consumer_index",
        "build_randomized_holdout_publication_registry_downstream_consumer_index",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_index_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_index_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_index_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_index_review": (
        "randomized_holdout_publication_registry_downstream_consumer_index_review",
        "build_randomized_holdout_publication_registry_downstream_consumer_index_review",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_index_review_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_index_review_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_index_review_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack": (
        "randomized_holdout_publication_registry_downstream_consumer_ack",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_check": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_check",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_check",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_check_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_check_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_check_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_review": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_review",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_review",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_review_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_review_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_review_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_check": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_check",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_check",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_check_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_check_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_check_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_index": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_index",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_index",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_index_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_index_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_index_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_index_review": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_index_review",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_index_review",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_index_review_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_index_review_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_index_review_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_review": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_review",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_review",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_review_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_review_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_review_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_check": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_check",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_check",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_check_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_check_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_check_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_review": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_review",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_review",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_review_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_review_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_review_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_check": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_check",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_check",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_check_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_check_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_check_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_index": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_index",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_index",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_index_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_index_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_index_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_index_review": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_index_review",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_index_review",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_index_review_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_index_review_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_index_review_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_review": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_review",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_review",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_review_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_review_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_review_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_check": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_check",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_check",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_check_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_check_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_check_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_review": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_review",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_review",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_review_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_review_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_review_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_check": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_check",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_check",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_check_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_check_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_check_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_index": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_index",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_index",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_index_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_index_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_index_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_index_review": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_index_review",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_index_review",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_index_review_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_index_review_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_index_review_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt_review": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt_review",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt_review",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt_review_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt_review_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt_review_outputs",
    ),
    "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt_packet": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt_packet",
        "build_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt_packet",
    ),
    "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt_packet_outputs": (
        "randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt_packet_artifacts",
        "write_randomized_holdout_publication_registry_downstream_consumer_ack_bundle_publication_receipt_packet_index_publication_receipt_packet_index_publication_receipt_packet_outputs",
    ),
    "build_model_capability_route_promotion_review_decision": (
        "model_capability_route_promotion_review_decision",
        "build_model_capability_route_promotion_review_decision",
    ),
    "write_model_capability_route_promotion_review_decision_outputs": (
        "model_capability_route_promotion_review_decision_artifacts",
        "write_model_capability_route_promotion_review_decision_outputs",
    ),
    "build_model_capability_route_promotion_decision_index": (
        "model_capability_route_promotion_decision_index",
        "build_model_capability_route_promotion_decision_index",
    ),
    "write_model_capability_route_promotion_decision_index_outputs": (
        "model_capability_route_promotion_decision_index_artifacts",
        "write_model_capability_route_promotion_decision_index_outputs",
    ),
    "build_model_capability_route_promotion_decision_index_check": (
        "model_capability_route_promotion_decision_index_check",
        "build_model_capability_route_promotion_decision_index_check",
    ),
    "write_model_capability_route_promotion_decision_index_check_outputs": (
        "model_capability_route_promotion_decision_index_check_artifacts",
        "write_model_capability_route_promotion_decision_index_check_outputs",
    ),
    "build_model_capability_route_promotion_governance_snapshot": (
        "model_capability_route_promotion_governance_snapshot",
        "build_model_capability_route_promotion_governance_snapshot",
    ),
    "write_model_capability_route_promotion_governance_snapshot_outputs": (
        "model_capability_route_promotion_governance_snapshot_artifacts",
        "write_model_capability_route_promotion_governance_snapshot_outputs",
    ),
    "build_model_capability_route_promotion_downstream_guard": (
        "model_capability_route_promotion_downstream_guard",
        "build_model_capability_route_promotion_downstream_guard",
    ),
    "write_model_capability_route_promotion_downstream_guard_outputs": (
        "model_capability_route_promotion_downstream_guard_artifacts",
        "write_model_capability_route_promotion_downstream_guard_outputs",
    ),
    "build_model_capability_route_promotion_consumer_plan": (
        "model_capability_route_promotion_consumer_plan",
        "build_model_capability_route_promotion_consumer_plan",
    ),
    "write_model_capability_route_promotion_consumer_plan_outputs": (
        "model_capability_route_promotion_consumer_plan_artifacts",
        "write_model_capability_route_promotion_consumer_plan_outputs",
    ),
    "build_model_capability_route_promotion_bounded_benchmark_suite": (
        "model_capability_route_promotion_bounded_benchmark_suite",
        "build_model_capability_route_promotion_bounded_benchmark_suite",
    ),
    "write_model_capability_route_promotion_bounded_benchmark_suite_outputs": (
        "model_capability_route_promotion_bounded_benchmark_suite_artifacts",
        "write_model_capability_route_promotion_bounded_benchmark_suite_outputs",
    ),
    "build_model_capability_route_promotion_bounded_benchmark_suite_review": (
        "model_capability_route_promotion_bounded_benchmark_suite_review",
        "build_model_capability_route_promotion_bounded_benchmark_suite_review",
    ),
    "write_model_capability_route_promotion_bounded_benchmark_suite_review_outputs": (
        "model_capability_route_promotion_bounded_benchmark_suite_review_artifacts",
        "write_model_capability_route_promotion_bounded_benchmark_suite_review_outputs",
    ),
    "build_model_capability_route_promotion_bounded_benchmark_dry_run": (
        "model_capability_route_promotion_bounded_benchmark_dry_run",
        "build_model_capability_route_promotion_bounded_benchmark_dry_run",
    ),
    "write_model_capability_route_promotion_bounded_benchmark_dry_run_outputs": (
        "model_capability_route_promotion_bounded_benchmark_dry_run_artifacts",
        "write_model_capability_route_promotion_bounded_benchmark_dry_run_outputs",
    ),
    "build_promoted_training_scale_seed_handoff_receipt_contract_summary": (
        "promoted_training_scale_seed_handoff_receipt_contract",
        "build_promoted_training_scale_seed_handoff_receipt_contract_summary",
    ),
    "write_promoted_training_scale_seed_handoff_receipt_contract_summary_outputs": (
        "promoted_training_scale_seed_handoff_receipt_contract",
        "write_promoted_training_scale_seed_handoff_receipt_contract_summary_outputs",
    ),
    "check_promoted_training_scale_seed_handoff_receipt_contract_summary": (
        "promoted_training_scale_seed_handoff_receipt_contract_check",
        "check_promoted_training_scale_seed_handoff_receipt_contract_summary",
    ),
    "write_promoted_training_scale_seed_handoff_receipt_contract_summary_check_outputs": (
        "promoted_training_scale_seed_handoff_receipt_contract_check",
        "write_promoted_training_scale_seed_handoff_receipt_contract_summary_check_outputs",
    ),
}


def __getattr__(name: str) -> Any:
    if name not in _EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr_name = _EXPORTS[name]
    value = getattr(import_module(f"{__name__}.{module_name}"), attr_name)
    globals()[name] = value
    return value
