from __future__ import annotations

from typing import Any

from minigpt.dashboard_sections import (
    artifact_grid as _artifact_grid,
    attention_section as _attention_section,
    chat_section as _chat_section,
    dataset_section as _dataset_section,
    eval_suite_section as _eval_suite_section,
    fmt as _fmt,
    fmt_int as _fmt_int,
    manifest_section as _manifest_section,
    model_section as _model_section,
    pair_batch_section as _pair_batch_section,
    prediction_section as _prediction_section,
    stats_grid as _stats_grid,
    style as _style,
    text_section as _text_section,
    training_section as _training_section,
    warning_section as _warning_section,
    escape as _e,
)

def render_dashboard_html(payload: dict[str, Any]) -> str:
    title = str(payload["title"])
    summary = payload["summary"]
    artifacts = payload["artifacts"]
    stats = [
        ("Artifacts", summary.get("available_artifacts")),
        ("Metrics", summary.get("metrics_records")),
        ("Tokenizer", summary.get("tokenizer")),
        ("Max iters", summary.get("max_iters")),
        ("Best val", _fmt(summary.get("best_val_loss"))),
        ("Eval loss", _fmt(summary.get("eval_loss"))),
        ("Perplexity", _fmt(summary.get("perplexity"))),
        ("Eval suite", summary.get("eval_suite_cases")),
        ("Pair batch", summary.get("pair_batch_cases")),
        ("Pair trend", summary.get("pair_trend_reports")),
        ("Data quality", summary.get("dataset_quality")),
        ("Git", summary.get("git_commit")),
        ("Parameters", _fmt_int(summary.get("total_parameters"))),
    ]

    sections = [
        _style(),
        f"<header><h1>{_e(title)}</h1><p>{_e(str(payload['run_dir']))}</p></header>",
        _stats_grid(stats),
        _artifact_grid(artifacts),
        _manifest_section(payload),
        _dataset_section(payload),
        _model_section(payload),
        _training_section(payload),
        _eval_suite_section(payload),
        _pair_batch_section(payload),
        _prediction_section(payload),
        _attention_section(payload),
        _chat_section(payload),
        _text_section("Sample", payload.get("sample_text")),
        _text_section("Generated", payload.get("generated_text")),
        _warning_section(payload.get("warnings", [])),
    ]
    return "\n".join(
        [
            "<!doctype html>",
            '<html lang="zh-CN">',
            "<head>",
            '<meta charset="utf-8">',
            '<meta name="viewport" content="width=device-width, initial-scale=1">',
            '<link rel="icon" href="data:,">',
            f"<title>{_e(title)}</title>",
            "</head>",
            "<body>",
            *sections,
            "<footer>Generated by MiniGPT dashboard exporter.</footer>",
            "</body>",
            "</html>",
        ]
    )


__all__ = ["render_dashboard_html"]
