from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from minigpt.report_utils import (
    as_dict as _dict,
    html_escape as _e,
    list_of_dicts as _list_of_dicts,
    write_json_payload,
)


def write_model_card_json(card: dict[str, Any], path: str | Path) -> None:
    write_json_payload(card, path)


def render_model_card_markdown(card: dict[str, Any]) -> str:
    summary = _dict(card.get("summary"))
    coverage = _dict(card.get("coverage"))
    lines = [
        f"# {card.get('title', 'MiniGPT model card')}",
        "",
        f"- Generated: `{card.get('generated_at')}`",
        f"- Registry: `{card.get('registry_path')}`",
        "",
        "## Summary",
        "",
        *_markdown_table(
            [
                ("Run count", summary.get("run_count")),
                ("Best run", summary.get("best_run_name")),
                ("Best val loss", _fmt(summary.get("best_val_loss"))),
                ("Ready runs", summary.get("ready_runs")),
                ("Review runs", summary.get("review_runs")),
                ("Experiment cards", coverage.get("experiment_cards_found")),
                ("Quality checked", coverage.get("quality_checked_runs")),
                ("Eval suite runs", coverage.get("eval_suite_runs")),
                ("Generation quality", coverage.get("generation_quality_runs")),
            ]
        ),
        "",
        "## Intended Use",
        "",
        *[f"- {item}" for item in _string_list(card.get("intended_use"))],
        "",
        "## Limitations",
        "",
        *[f"- {item}" for item in _string_list(card.get("limitations"))],
        "",
        "## Top Runs",
        "",
        *_run_table(_list_of_dicts(card.get("top_runs"))),
        "",
        "## Coverage",
        "",
        *_markdown_table([(key, value) for key, value in coverage.items()]),
        "",
        "## Recommendations",
        "",
        *[f"- {item}" for item in _string_list(card.get("recommendations"))],
        "",
        "## Runs",
        "",
        *_run_table(_list_of_dicts(card.get("runs"))),
    ]
    warnings = _string_list(card.get("warnings"))
    if warnings:
        lines.extend(["", "## Warnings", "", *[f"- {item}" for item in warnings]])
    return "\n".join(lines).rstrip() + "\n"


def write_model_card_markdown(card: dict[str, Any], path: str | Path) -> None:
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_model_card_markdown(card), encoding="utf-8")


def render_model_card_html(card: dict[str, Any], *, base_dir: str | Path | None = None) -> str:
    summary = _dict(card.get("summary"))
    coverage = _dict(card.get("coverage"))
    stats = [
        ("Runs", summary.get("run_count")),
        ("Best run", summary.get("best_run_name")),
        ("Best val", _fmt(summary.get("best_val_loss"))),
        ("Ready", summary.get("ready_runs")),
        ("Review", summary.get("review_runs")),
        ("Cards", coverage.get("experiment_cards_found")),
        ("Eval suite", coverage.get("eval_suite_runs")),
        ("Gen quality", coverage.get("generation_quality_runs")),
        ("Quality", coverage.get("quality_checked_runs")),
    ]
    return "\n".join(
        [
            "<!doctype html>",
            '<html lang="zh-CN">',
            "<head>",
            '<meta charset="utf-8">',
            '<meta name="viewport" content="width=device-width, initial-scale=1">',
            '<link rel="icon" href="data:,">',
            f"<title>{_e(card.get('title', 'MiniGPT model card'))}</title>",
            _style(),
            "</head>",
            "<body>",
            f"<header><h1>{_e(card.get('title', 'MiniGPT model card'))}</h1><p>{_e(card.get('registry_path'))}</p></header>",
            '<section class="stats">' + "".join(_stat(label, value) for label, value in stats) + "</section>",
            _list_section("Intended Use", card.get("intended_use")),
            _list_section("Limitations", card.get("limitations")),
            _run_section("Top Runs", _list_of_dicts(card.get("top_runs")), base_dir),
            _key_value_section("Coverage", coverage),
            _key_value_section("Quality Counts", _dict(card.get("quality_counts"))),
            _key_value_section("Generation Quality Counts", _dict(card.get("generation_quality_counts"))),
            _key_value_section("Tag Counts", _dict(card.get("tag_counts"))),
            _list_section("Recommendations", card.get("recommendations")),
            _run_section("All Runs", _list_of_dicts(card.get("runs")), base_dir),
            _list_section("Warnings", card.get("warnings"), hide_empty=True),
            "<footer>Generated by MiniGPT model card exporter.</footer>",
            "</body>",
            "</html>",
        ]
    )


def write_model_card_html(card: dict[str, Any], path: str | Path) -> None:
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_model_card_html(card, base_dir=out_path.parent), encoding="utf-8")


def write_model_card_outputs(card: dict[str, Any], out_dir: str | Path) -> dict[str, str]:
    root = Path(out_dir)
    root.mkdir(parents=True, exist_ok=True)
    paths = {
        "json": root / "model_card.json",
        "markdown": root / "model_card.md",
        "html": root / "model_card.html",
    }
    write_model_card_json(card, paths["json"])
    write_model_card_markdown(card, paths["markdown"])
    write_model_card_html(card, paths["html"])
    return {key: str(value) for key, value in paths.items()}


def _run_table(runs: list[dict[str, Any]]) -> list[str]:
    lines = ["| Rank | Run | Status | Best Val | Delta | Quality | Eval | Gen Quality | Card |", "| --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
    for run in runs:
        lines.append(
            "| "
            + " | ".join(
                [
                    _md(_rank_label(run.get("best_val_loss_rank"))),
                    _md(run.get("name")),
                    _md(run.get("status")),
                    _md(_fmt(run.get("best_val_loss"))),
                    _md(_fmt_delta(run.get("best_val_loss_delta"))),
                    _md(run.get("dataset_quality")),
                    _md(run.get("eval_suite_cases")),
                    _md(_generation_quality_label(run)),
                    _md("yes" if run.get("experiment_card_exists") else "no"),
                ]
            )
            + " |"
        )
    return lines


def _run_section(title: str, runs: list[dict[str, Any]], base_dir: str | Path | None) -> str:
    rows = []
    for run in runs:
        card = run.get("experiment_card_html") or run.get("experiment_card_path")
        card_link = _path_link(card, base_dir, "card") if card else '<span class="muted">missing</span>'
        rows.append(
            "<tr>"
            f"<td>{_e(_rank_label(run.get('best_val_loss_rank')))}</td>"
            f"<td><strong>{_e(run.get('name'))}</strong><br><span>{_e(run.get('path'))}</span></td>"
            f"<td>{_e(run.get('status'))}</td>"
            f"<td>{_e(_fmt(run.get('best_val_loss')))}<br><span>{_e(_fmt_delta(run.get('best_val_loss_delta')))}</span></td>"
            f"<td>{_e(run.get('dataset_quality'))}</td>"
            f"<td>{_e(run.get('eval_suite_cases'))}</td>"
            f"<td>{_e(_generation_quality_label(run))}</td>"
            f"<td>{_tag_chips(run.get('tags'))}<br><span>{_e(run.get('note'))}</span></td>"
            f"<td>{card_link}</td>"
            "</tr>"
        )
    return (
        f'<section class="panel"><h2>{_e(title)}</h2>'
        '<table><thead><tr><th>Rank</th><th>Run</th><th>Status</th><th>Best Val</th><th>Quality</th><th>Eval</th><th>Gen Quality</th><th>Notes</th><th>Card</th></tr></thead><tbody>'
        + "".join(rows)
        + "</tbody></table></section>"
    )


def _key_value_section(title: str, payload: dict[str, Any]) -> str:
    rows = "".join(f"<tr><th>{_e(key)}</th><td>{_e(_fmt_any(value))}</td></tr>" for key, value in payload.items())
    return f'<section class="panel"><h2>{_e(title)}</h2><table>{rows}</table></section>'


def _list_section(title: str, values: Any, hide_empty: bool = False) -> str:
    items = _string_list(values)
    if hide_empty and not items:
        return ""
    if not items:
        items = ["missing"]
    return f'<section class="panel"><h2>{_e(title)}</h2><ul>' + "".join(f"<li>{_e(item)}</li>" for item in items) + "</ul></section>"


def _stat(label: str, value: Any) -> str:
    return '<div class="card">' + f'<div class="label">{_e(label)}</div><div class="value">{_e(_fmt_any(value))}</div>' + "</div>"


def _path_link(path: Any, base_dir: str | Path | None, label: str) -> str:
    if path is None:
        return '<span class="muted">missing</span>'
    href = str(path)
    if base_dir is not None:
        try:
            href = Path(os.path.relpath(Path(str(path)), Path(base_dir))).as_posix()
        except ValueError:
            href = Path(str(path)).as_posix()
    return f'<a href="{_e(href)}">{_e(label)}</a>'


def _style() -> str:
    return """<style>
:root { --ink:#111827; --muted:#4b5563; --line:#d8dee9; --page:#f7f7f2; --panel:#fff; --blue:#2563eb; }
* { box-sizing:border-box; }
body { margin:0; background:var(--page); color:var(--ink); font-family:Arial, "Microsoft YaHei", sans-serif; line-height:1.45; }
header { padding:28px 32px 18px; background:#fff; border-bottom:1px solid var(--line); }
h1 { margin:0 0 8px; font-size:28px; letter-spacing:0; }
h2 { margin:0 0 12px; font-size:18px; }
span, .muted { color:var(--muted); }
.stats { display:grid; grid-template-columns:repeat(auto-fit, minmax(150px, 1fr)); gap:12px; padding:18px 32px 4px; }
.card, .panel { background:var(--panel); border:1px solid var(--line); border-radius:8px; }
.card { padding:14px; min-height:82px; }
.label { color:var(--muted); font-size:12px; text-transform:uppercase; }
.value { margin-top:6px; font-size:20px; font-weight:700; overflow-wrap:anywhere; }
.panel { margin:18px 32px; padding:16px; overflow-x:auto; }
table { width:100%; border-collapse:collapse; min-width:920px; }
th, td { padding:8px; border-bottom:1px solid var(--line); text-align:left; vertical-align:top; }
th { color:var(--muted); font-size:12px; text-transform:uppercase; }
a { color:var(--blue); font-weight:700; text-decoration:none; }
.tag { display:inline-block; margin:0 4px 4px 0; padding:2px 6px; border-radius:999px; background:#e0f2fe; color:#075985; font-size:12px; font-weight:700; }
footer { padding:20px 32px 34px; color:var(--muted); font-size:13px; }
@media (max-width:760px) { header, .stats { padding-left:16px; padding-right:16px; } .panel { margin-left:16px; margin-right:16px; } }
</style>"""


def _markdown_table(rows: list[tuple[str, Any]]) -> list[str]:
    lines = ["| Field | Value |", "| --- | --- |"]
    for key, value in rows:
        lines.append(f"| {_md(key)} | {_md(value)} |")
    return lines


def _tag_chips(value: Any) -> str:
    tags = _as_str_list(value)
    if not tags:
        return '<span class="muted">missing</span>'
    return "".join(f'<span class="tag">{_e(tag)}</span>' for tag in tags)


def _generation_quality_label(run: dict[str, Any]) -> str:
    status = run.get("generation_quality_status") or "missing"
    cases = run.get("generation_quality_cases")
    if cases in {None, ""}:
        return str(status)
    return f"{status} ({cases} cases)"


def _string_list(value: Any) -> list[str]:
    return [str(item) for item in value if str(item).strip()] if isinstance(value, list) else []


def _as_str_list(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        return [item.strip() for item in value.split(",") if item.strip()]
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    return [str(value).strip()] if str(value).strip() else []


def _fmt(value: Any) -> str:
    if value is None:
        return "missing"
    if isinstance(value, float):
        return f"{value:.5g}"
    return str(value)


def _fmt_delta(value: Any) -> str:
    if value is None or value == "":
        return "missing"
    return f"{float(value):+.5g}"


def _fmt_any(value: Any) -> str:
    if isinstance(value, dict):
        return ", ".join(f"{key}:{val}" for key, val in value.items()) or "missing"
    if isinstance(value, list):
        return ", ".join(str(item) for item in value) or "missing"
    if isinstance(value, float):
        return f"{value:.5g}"
    return "missing" if value is None else str(value)


def _rank_label(value: Any) -> str:
    if value is None or value == "":
        return "unranked"
    return f"#{int(value)}"


def _md(value: Any) -> str:
    return _fmt_any(value).replace("|", "\\|").replace("\n", " ")


__all__ = [
    "render_model_card_html",
    "render_model_card_markdown",
    "write_model_card_html",
    "write_model_card_json",
    "write_model_card_markdown",
    "write_model_card_outputs",
]
