from __future__ import annotations

from pathlib import Path
from typing import Any

from minigpt.report_utils import (
    as_dict as _dict,
    html_escape as _e,
    list_of_dicts as _list_of_dicts,
    write_json_payload,
)


def write_project_audit_json(audit: dict[str, Any], path: str | Path) -> None:
    write_json_payload(audit, path)


def render_project_audit_markdown(audit: dict[str, Any]) -> str:
    summary = _dict(audit.get("summary"))
    lines = [
        f"# {audit.get('title', 'MiniGPT project audit')}",
        "",
        f"- Generated: `{audit.get('generated_at')}`",
        f"- Registry: `{audit.get('registry_path')}`",
        f"- Model card: `{audit.get('model_card_path') or 'missing'}`",
        f"- Request history summary: `{audit.get('request_history_summary_path') or 'missing'}`",
        "",
        "## Summary",
        "",
        *_markdown_table(
            [
                ("Overall status", summary.get("overall_status")),
                ("Score", summary.get("score_percent")),
                ("Runs", summary.get("run_count")),
                ("Best run", summary.get("best_run_name")),
                ("Ready runs", summary.get("ready_runs")),
                ("Request history status", summary.get("request_history_status")),
                ("Request history records", summary.get("request_history_records")),
                ("Pass checks", summary.get("pass_count")),
                ("Warn checks", summary.get("warn_count")),
                ("Fail checks", summary.get("fail_count")),
            ]
        ),
        "",
        "## Checks",
        "",
        "| Status | Check | Detail |",
        "| --- | --- | --- |",
    ]
    for check in _list_of_dicts(audit.get("checks")):
        lines.append(f"| {_md(check.get('status'))} | {_md(check.get('title'))} | {_md(check.get('detail'))} |")
    lines.extend(["", "## Recommendations", ""])
    lines.extend(f"- {item}" for item in _string_list(audit.get("recommendations")))
    lines.extend(["", "## Runs", ""])
    lines.extend(_run_table(_list_of_dicts(audit.get("runs"))))
    warnings = _string_list(audit.get("warnings"))
    if warnings:
        lines.extend(["", "## Warnings", ""])
        lines.extend(f"- {item}" for item in warnings)
    return "\n".join(lines).rstrip() + "\n"


def write_project_audit_markdown(audit: dict[str, Any], path: str | Path) -> None:
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_project_audit_markdown(audit), encoding="utf-8")


def render_project_audit_html(audit: dict[str, Any]) -> str:
    summary = _dict(audit.get("summary"))
    stats = [
        ("Status", summary.get("overall_status")),
        ("Score", f"{summary.get('score_percent')}%"),
        ("Runs", summary.get("run_count")),
        ("Best run", summary.get("best_run_name")),
        ("Ready", summary.get("ready_runs")),
        ("Req history", summary.get("request_history_status")),
        ("Pass", summary.get("pass_count")),
        ("Warn", summary.get("warn_count")),
        ("Fail", summary.get("fail_count")),
    ]
    return "\n".join(
        [
            "<!doctype html>",
            '<html lang="zh-CN">',
            "<head>",
            '<meta charset="utf-8">',
            '<meta name="viewport" content="width=device-width, initial-scale=1">',
            '<link rel="icon" href="data:,">',
            f"<title>{_e(audit.get('title', 'MiniGPT project audit'))}</title>",
            _style(),
            "</head>",
            "<body>",
            f"<header><h1>{_e(audit.get('title', 'MiniGPT project audit'))}</h1><p>{_e(audit.get('registry_path'))}</p></header>",
            '<section class="stats">' + "".join(_stat_card(label, value) for label, value in stats) + "</section>",
            _check_section(_list_of_dicts(audit.get("checks"))),
            _list_section("Recommendations", audit.get("recommendations")),
            _run_section(_list_of_dicts(audit.get("runs"))),
            _list_section("Warnings", audit.get("warnings"), hide_empty=True),
            "<footer>Generated by MiniGPT project audit exporter.</footer>",
            "</body>",
            "</html>",
        ]
    )


def write_project_audit_html(audit: dict[str, Any], path: str | Path) -> None:
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_project_audit_html(audit), encoding="utf-8")


def write_project_audit_outputs(audit: dict[str, Any], out_dir: str | Path) -> dict[str, str]:
    root = Path(out_dir)
    root.mkdir(parents=True, exist_ok=True)
    paths = {
        "json": root / "project_audit.json",
        "markdown": root / "project_audit.md",
        "html": root / "project_audit.html",
    }
    write_project_audit_json(audit, paths["json"])
    write_project_audit_markdown(audit, paths["markdown"])
    write_project_audit_html(audit, paths["html"])
    return {key: str(value) for key, value in paths.items()}


def _check_section(checks: list[dict[str, Any]]) -> str:
    rows = []
    for check in checks:
        status = str(check.get("status") or "missing")
        rows.append(
            "<tr>"
            f'<td><span class="pill {status}">{_e(status)}</span></td>'
            f"<td><strong>{_e(check.get('title'))}</strong><br><span>{_e(check.get('id'))}</span></td>"
            f"<td>{_e(check.get('detail'))}</td>"
            "</tr>"
        )
    return '<section class="panel"><h2>Checks</h2><table><thead><tr><th>Status</th><th>Check</th><th>Detail</th></tr></thead><tbody>' + "".join(rows) + "</tbody></table></section>"


def _run_section(runs: list[dict[str, Any]]) -> str:
    rows = []
    for run in runs:
        rows.append(
            "<tr>"
            f"<td>{_e(_rank_label(run.get('best_val_loss_rank')))}</td>"
            f"<td><strong>{_e(run.get('name'))}</strong><br><span>{_e(run.get('path'))}</span></td>"
            f"<td>{_e(run.get('status'))}</td>"
            f"<td>{_e(_fmt(run.get('best_val_loss')))}<br><span>{_e(_fmt_delta(run.get('best_val_loss_delta')))}</span></td>"
            f"<td>{_e(run.get('dataset_quality'))}</td>"
            f"<td>{_e(run.get('eval_suite_cases'))}</td>"
            f"<td>{_e(_generation_quality_label(run))}</td>"
            f"<td>{_e('yes' if run.get('experiment_card_exists') else 'no')}</td>"
            "</tr>"
        )
    return '<section class="panel"><h2>Runs</h2><table><thead><tr><th>Rank</th><th>Run</th><th>Status</th><th>Best Val</th><th>Quality</th><th>Eval</th><th>Gen Quality</th><th>Card</th></tr></thead><tbody>' + "".join(rows) + "</tbody></table></section>"


def _run_table(runs: list[dict[str, Any]]) -> list[str]:
    lines = ["| Rank | Run | Status | Best Val | Quality | Eval | Gen Quality | Card |", "| --- | --- | --- | --- | --- | --- | --- | --- |"]
    for run in runs:
        lines.append(
            "| "
            + " | ".join(
                [
                    _md(_rank_label(run.get("best_val_loss_rank"))),
                    _md(run.get("name")),
                    _md(run.get("status")),
                    _md(_fmt(run.get("best_val_loss"))),
                    _md(run.get("dataset_quality")),
                    _md(run.get("eval_suite_cases")),
                    _md(_generation_quality_label(run)),
                    _md("yes" if run.get("experiment_card_exists") else "no"),
                ]
            )
            + " |"
        )
    return lines


def _list_section(title: str, values: Any, hide_empty: bool = False) -> str:
    items = _string_list(values)
    if hide_empty and not items:
        return ""
    if not items:
        items = ["missing"]
    return f'<section class="panel"><h2>{_e(title)}</h2><ul>' + "".join(f"<li>{_e(item)}</li>" for item in items) + "</ul></section>"


def _stat_card(label: str, value: Any) -> str:
    return '<div class="card">' + f'<div class="label">{_e(label)}</div><div class="value">{_e(_fmt_any(value))}</div>' + "</div>"


def _style() -> str:
    return """<style>
:root { --ink:#111827; --muted:#4b5563; --line:#d8dee9; --page:#f7f7f2; --panel:#fff; --blue:#2563eb; --green:#047857; --amber:#b45309; --red:#b91c1c; }
* { box-sizing:border-box; }
body { margin:0; background:var(--page); color:var(--ink); font-family:Arial, "Microsoft YaHei", sans-serif; line-height:1.45; }
header { padding:28px 32px 18px; background:#fff; border-bottom:1px solid var(--line); }
h1 { margin:0 0 8px; font-size:28px; letter-spacing:0; }
h2 { margin:0 0 12px; font-size:18px; }
span, .muted { color:var(--muted); }
.stats { display:grid; grid-template-columns:repeat(auto-fit, minmax(150px, 1fr)); gap:12px; padding:18px 32px 4px; }
.card, .panel { background:var(--panel); border:1px solid var(--line); border-radius:8px; }
.card { padding:14px; min-height:82px; }
.label { color:var(--muted); font-size:12px; text-transform:uppercase; }
.value { margin-top:6px; font-size:20px; font-weight:700; overflow-wrap:anywhere; }
.panel { margin:18px 32px; padding:16px; overflow-x:auto; }
table { width:100%; border-collapse:collapse; min-width:860px; }
th, td { padding:8px; border-bottom:1px solid var(--line); text-align:left; vertical-align:top; }
th { color:var(--muted); font-size:12px; text-transform:uppercase; }
.pill { display:inline-block; min-width:54px; padding:3px 8px; border-radius:999px; color:#fff; text-align:center; font-size:12px; font-weight:700; }
.pill.pass { background:var(--green); }
.pill.warn { background:var(--amber); }
.pill.fail { background:var(--red); }
footer { padding:20px 32px 34px; color:var(--muted); font-size:13px; }
@media (max-width:760px) { header, .stats { padding-left:16px; padding-right:16px; } .panel { margin-left:16px; margin-right:16px; } }
</style>"""


def _markdown_table(rows: list[tuple[str, Any]]) -> list[str]:
    lines = ["| Field | Value |", "| --- | --- |"]
    for key, value in rows:
        lines.append(f"| {_md(key)} | {_md(value)} |")
    return lines


def _rank_label(value: Any) -> str:
    if value is None or value == "":
        return "unranked"
    return f"#{int(value)}"


def _generation_quality_label(run: dict[str, Any]) -> str:
    status = run.get("generation_quality_status") or "missing"
    cases = run.get("generation_quality_cases")
    if cases in {None, ""}:
        return str(status)
    return f"{status} ({cases} cases)"


def _fmt(value: Any) -> str:
    if value is None:
        return "missing"
    if isinstance(value, float):
        return f"{value:.5g}"
    return str(value)


def _fmt_delta(value: Any) -> str:
    if value is None or value == "":
        return "missing"
    return f"{float(value):+.5g}"


def _fmt_any(value: Any) -> str:
    if isinstance(value, float):
        return f"{value:.5g}"
    return "missing" if value is None else str(value)


def _string_list(value: Any) -> list[str]:
    return [str(item) for item in value if str(item).strip()] if isinstance(value, list) else []


def _md(value: Any) -> str:
    return _fmt_any(value).replace("|", "\\|").replace("\n", " ")
