from __future__ import annotations

from typing import Any

from minigpt.report_utils import (
    as_dict as _dict,
    format_mapping as _fmt_mapping,
    html_escape as _e,
    list_of_dicts as _list_of_dicts,
    string_list as _string_list,
)


def render_promoted_training_scale_seed_html(report: dict[str, Any]) -> str:
    seed = _dict(report.get("baseline_seed"))
    plan = _dict(report.get("next_plan"))
    summary = _dict(report.get("summary"))
    stats = [
        ("Status", report.get("seed_status")),
        ("Baseline", seed.get("selected_name")),
        ("Decision", seed.get("decision_status")),
        ("Gate", seed.get("gate_status")),
        ("Batch", seed.get("batch_status")),
        ("Score", seed.get("readiness_score")),
        ("Sources", summary.get("source_count")),
        ("Missing", summary.get("missing_source_count")),
        ("Selected handoff suite", summary.get("selected_handoff_suite_consistency")),
        ("Selected handoff mismatch", summary.get("selected_handoff_suite_mismatch_count")),
        ("Selected clean required", summary.get("selected_handoff_require_clean_batch_review")),
        ("Selected clean batch", summary.get("selected_handoff_clean_batch_review_status")),
        ("Selected CI regressions", summary.get("selected_handoff_batch_maturity_ci_regression_count")),
        ("Selected CI reasons", _fmt_mapping(summary.get("selected_handoff_batch_maturity_ci_regression_reason_counts"))),
        ("Selected selected CI regressions", summary.get("selected_handoff_selected_batch_maturity_ci_regression_count")),
        (
            "Selected selected CI reasons",
            _fmt_mapping(summary.get("selected_handoff_selected_batch_maturity_ci_regression_reason_counts")),
        ),
        ("Handoff clean required", summary.get("handoff_require_clean_batch_review_count")),
        ("Handoff clean", summary.get("handoff_clean_batch_review_count")),
        ("Handoff unclean", summary.get("handoff_unclean_batch_review_count")),
        ("Handoff CI regressions", summary.get("handoff_batch_maturity_ci_regression_count")),
        ("Handoff CI reasons", _fmt_mapping(summary.get("handoff_batch_maturity_ci_regression_reason_counts"))),
        ("Handoff selected CI regressions", summary.get("handoff_selected_batch_maturity_ci_regression_total")),
        (
            "Handoff selected CI reasons",
            _fmt_mapping(summary.get("handoff_selected_batch_maturity_ci_regression_reason_counts")),
        ),
        ("Ready clean-required", summary.get("comparison_ready_handoff_require_clean_batch_review_count")),
        ("Ready clean batch", summary.get("comparison_ready_handoff_clean_batch_review_count")),
        ("Ready unclean batch", summary.get("comparison_ready_handoff_unclean_batch_review_count")),
        ("Ready CI regressions", summary.get("comparison_ready_handoff_batch_maturity_ci_regression_count")),
        (
            "Ready CI reasons",
            _fmt_mapping(summary.get("comparison_ready_handoff_batch_maturity_ci_regression_reason_counts")),
        ),
        (
            "Ready selected CI regressions",
            summary.get("comparison_ready_handoff_selected_batch_maturity_ci_regression_total"),
        ),
        (
            "Ready selected CI reasons",
            _fmt_mapping(summary.get("comparison_ready_handoff_selected_batch_maturity_ci_regression_reason_counts")),
        ),
        ("Selected handoff batch", summary.get("selected_handoff_selected_batch_review_status")),
        ("Selected batch blockers", summary.get("selected_handoff_selected_batch_comparison_blocker_action_count")),
        ("Ready batch reviews", summary.get("comparison_ready_handoff_selected_batch_review_count")),
        ("Ready batch blockers", summary.get("comparison_ready_handoff_selected_batch_blocker_count")),
        ("Handoff suite mismatches", summary.get("handoff_suite_mismatch_total")),
        ("Next suite", summary.get("next_suite_path")),
    ]
    return "\n".join(
        [
            "<!doctype html>",
            '<html lang="zh-CN">',
            "<head>",
            '<meta charset="utf-8">',
            '<meta name="viewport" content="width=device-width, initial-scale=1">',
            '<link rel="icon" href="data:,">',
            f"<title>{_e(report.get('title', 'MiniGPT promoted training scale next-cycle seed'))}</title>",
            _style(),
            "</head>",
            "<body>",
            f"<header><h1>{_e(report.get('title', 'MiniGPT promoted training scale next-cycle seed'))}</h1><p>{_e(report.get('decision_path'))}</p></header>",
            '<section class="stats">' + "".join(_card(label, value) for label, value in stats) + "</section>",
            _baseline_section(seed),
            _command_section(plan),
            _source_table(plan),
            _list_section("Blockers", report.get("blockers")),
            _list_section("Recommendations", report.get("recommendations")),
            "<footer>Generated by MiniGPT promoted training scale next-cycle seed.</footer>",
            "</body>",
            "</html>",
        ]
    )


def _baseline_section(seed: dict[str, Any]) -> str:
    rows = [
        ("Selected baseline", seed.get("selected_name")),
        ("Decision status", seed.get("decision_status")),
        ("Training scale run", seed.get("training_scale_run_path")),
        ("Run exists", seed.get("training_scale_run_exists")),
        ("Comparison", seed.get("comparison_path")),
    ]
    guard = _dict(seed.get("handoff_suite_guard"))
    rows.extend(
        [
            ("Selected handoff strict", guard.get("selected_handoff_require_suite_consistency")),
            ("Selected handoff suite", guard.get("selected_handoff_suite_consistency")),
            ("Selected handoff mismatch", guard.get("selected_handoff_suite_mismatch_count")),
            ("Selected handoff suite path", guard.get("selected_handoff_selected_suite_path")),
        ]
    )
    clean_review = _dict(seed.get("handoff_clean_batch_review"))
    rows.extend(
        [
            ("Selected clean required", clean_review.get("selected_handoff_require_clean_batch_review")),
            ("Selected clean batch", clean_review.get("selected_handoff_clean_batch_review_status")),
            ("Selected CI regressions", clean_review.get("selected_handoff_batch_maturity_ci_regression_count")),
            (
                "Selected CI reasons",
                _fmt_mapping(clean_review.get("selected_handoff_batch_maturity_ci_regression_reason_counts")),
            ),
            (
                "Selected selected CI regressions",
                clean_review.get("selected_handoff_selected_batch_maturity_ci_regression_count"),
            ),
            (
                "Selected selected CI reasons",
                _fmt_mapping(clean_review.get("selected_handoff_selected_batch_maturity_ci_regression_reason_counts")),
            ),
            (
                "Selected comparison exclusions",
                ", ".join(_string_list(clean_review.get("selected_comparison_exclusion_reasons"))),
            ),
            ("Handoff clean required", clean_review.get("handoff_require_clean_batch_review_count")),
            ("Handoff clean", clean_review.get("handoff_clean_batch_review_count")),
            ("Handoff unclean", clean_review.get("handoff_unclean_batch_review_count")),
            ("Handoff CI regressions", clean_review.get("handoff_batch_maturity_ci_regression_count")),
            ("Handoff CI reasons", _fmt_mapping(clean_review.get("handoff_batch_maturity_ci_regression_reason_counts"))),
            (
                "Handoff CI-regressed names",
                ", ".join(_string_list(clean_review.get("handoff_batch_maturity_ci_regression_names"))),
            ),
            (
                "Comparison exclusions",
                ", ".join(_string_list(clean_review.get("comparison_exclusion_reasons"))),
            ),
            (
                "Comparison-ready clean-required",
                clean_review.get("comparison_ready_handoff_require_clean_batch_review_count"),
            ),
            ("Comparison-ready clean", clean_review.get("comparison_ready_handoff_clean_batch_review_count")),
            ("Comparison-ready unclean", clean_review.get("comparison_ready_handoff_unclean_batch_review_count")),
            (
                "Comparison-ready CI regressions",
                clean_review.get("comparison_ready_handoff_batch_maturity_ci_regression_count"),
            ),
        ]
    )
    batch_review = _dict(seed.get("handoff_batch_review"))
    rows.extend(
        [
            ("Selected handoff batch review", batch_review.get("selected_handoff_selected_batch_review_status")),
            (
                "Selected handoff batch review actions",
                batch_review.get("selected_handoff_selected_batch_comparison_review_action_count"),
            ),
            (
                "Selected handoff batch blocker actions",
                batch_review.get("selected_handoff_selected_batch_comparison_blocker_action_count"),
            ),
            (
                "Selected handoff batch blocker reasons",
                ", ".join(_string_list(batch_review.get("selected_handoff_batch_comparison_blocker_reasons"))),
            ),
            (
                "Comparison-ready batch blockers",
                batch_review.get("comparison_ready_handoff_selected_batch_blocker_count"),
            ),
        ]
    )
    summary = _dict(seed.get("selected_run_summary"))
    rows.extend(
        [
            ("Source scale tier", summary.get("scale_tier")),
            ("Source characters", summary.get("char_count")),
            ("Source variants", summary.get("variant_count")),
            ("Source suite mode", summary.get("suite_mode")),
            ("Source suite name", summary.get("suite_name")),
            ("Source suite path", summary.get("suite_path")),
        ]
    )
    body = "".join(f"<tr><th>{_e(label)}</th><td>{_e(value)}</td></tr>" for label, value in rows)
    return f"<section><h2>Baseline Seed</h2><table>{body}</table></section>"


def _command_section(plan: dict[str, Any]) -> str:
    command = str(plan.get("command_text") or "No command is available until blockers are fixed.")
    return f"<section><h2>Next Plan Command</h2><pre>{_e(command)}</pre></section>"


def _source_table(plan: dict[str, Any]) -> str:
    rows = []
    for row in _list_of_dicts(plan.get("sources")):
        rows.append(
            "<tr>"
            f"<td>{_e(row.get('path'))}</td>"
            f"<td>{_e(row.get('exists'))}</td>"
            f"<td>{_e(row.get('kind'))}</td>"
            "</tr>"
        )
    if not rows:
        return "<section><h2>Sources</h2><p>No sources provided.</p></section>"
    return (
        '<section><h2>Sources</h2><div class="table-wrap"><table>'
        "<thead><tr><th>Source</th><th>Exists</th><th>Kind</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table></div></section>"
    )


def _list_section(title: str, items: Any) -> str:
    values = _string_list(items)
    if not values:
        return ""
    return f"<section><h2>{_e(title)}</h2><ul>{''.join(f'<li>{_e(item)}</li>' for item in values)}</ul></section>"


def _style() -> str:
    return """<style>
:root { color-scheme: light; font-family: "Segoe UI", Arial, sans-serif; background: #f7f8f3; color: #172026; }
body { margin: 0; padding: 28px; }
header, section, footer { max-width: 1180px; margin: 0 auto 18px; }
header { border-bottom: 1px solid #d7dccf; padding-bottom: 18px; }
h1 { font-size: 30px; margin: 0 0 8px; letter-spacing: 0; }
h2 { font-size: 18px; margin: 0 0 12px; letter-spacing: 0; }
p { color: #4f5d52; }
.stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(132px, 1fr)); gap: 10px; }
.card, section { background: #ffffff; border: 1px solid #d9ded7; border-radius: 8px; padding: 14px; box-shadow: 0 1px 2px rgba(23, 32, 38, 0.05); }
.card span { display: block; color: #667366; font-size: 12px; }
.card strong { display: block; margin-top: 6px; font-size: 16px; overflow-wrap: anywhere; }
.table-wrap { overflow-x: auto; }
table { width: 100%; border-collapse: collapse; min-width: 760px; }
th, td { text-align: left; border-bottom: 1px solid #e3e7df; padding: 9px; vertical-align: top; }
th { color: #435047; font-size: 12px; text-transform: uppercase; width: 190px; }
pre { white-space: pre-wrap; overflow-wrap: anywhere; background: #172026; color: #f7faf2; border-radius: 8px; padding: 12px; }
li { margin: 7px 0; }
footer { color: #69756a; font-size: 12px; }
</style>"""


def _card(label: str, value: Any) -> str:
    return f'<div class="card"><span>{_e(label)}</span><strong>{_e(value)}</strong></div>'


__all__ = ["render_promoted_training_scale_seed_html"]
