from __future__ import annotations

import csv
from pathlib import Path
from typing import Any

from minigpt.report_utils import (
    as_dict,
    csv_cell,
    html_escape,
    markdown_cell,
    string_list,
    write_output_bundle,
    write_json_payload,
)


def render_readability_text(report: dict[str, Any]) -> str:
    summary = as_dict(report.get("summary"))
    lines = [
        f"status={report.get('status')}",
        f"decision={report.get('decision')}",
    ]
    for key, value in summary.items():
        if isinstance(value, (str, int, float, bool)) or value is None:
            lines.append(f"{key}={value}")
    return "\n".join(lines).rstrip() + "\n"


def render_readability_markdown(report: dict[str, Any], *, row_title: str = "Rows", row_key: str = "rows") -> str:
    summary = as_dict(report.get("summary"))
    rows = _rows(report, row_key)
    fieldnames = _fieldnames(report, rows)
    lines = [
        f"# {report.get('title', 'MiniGPT readability report')}",
        "",
        f"- Generated: `{report.get('generated_at')}`",
        f"- Status: `{report.get('status')}`",
        f"- Decision: `{report.get('decision')}`",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "| --- | --- |",
    ]
    for key, value in summary.items():
        lines.append(f"| {markdown_cell(key)} | {markdown_cell(_display(value))} |")
    lines.extend(["", f"## {row_title}", ""])
    if rows:
        lines.append("| " + " | ".join(markdown_cell(field) for field in fieldnames) + " |")
        lines.append("| " + " | ".join("---" for _ in fieldnames) + " |")
        for row in rows:
            lines.append("| " + " | ".join(markdown_cell(_display(row.get(field))) for field in fieldnames) + " |")
    else:
        lines.append("No rows.")
    recommendations = string_list(report.get("recommendations"))
    if recommendations:
        lines.extend(["", "## Recommendations", ""])
        lines.extend(f"- {item}" for item in recommendations)
    return "\n".join(lines).rstrip() + "\n"


def render_readability_html(report: dict[str, Any], *, row_title: str = "Rows", row_key: str = "rows") -> str:
    summary = as_dict(report.get("summary"))
    rows = _rows(report, row_key)
    fieldnames = _fieldnames(report, rows)
    stat_html = "".join(_stat(str(key), _display(value)) for key, value in summary.items())
    if not stat_html:
        stat_html = _stat("status", report.get("status"))
    if rows:
        row_html = "".join(
            "<tr>" + "".join(f"<td>{html_escape(_display(row.get(field)))}</td>" for field in fieldnames) + "</tr>"
            for row in rows
        )
        table_html = (
            "<table><thead><tr>"
            + "".join(f"<th>{html_escape(field)}</th>" for field in fieldnames)
            + "</tr></thead><tbody>"
            + row_html
            + "</tbody></table>"
        )
    else:
        table_html = '<p class="muted">No rows.</p>'
    recommendations = "".join(f"<li>{html_escape(item)}</li>" for item in string_list(report.get("recommendations")))
    if recommendations:
        recommendations = f"<section><h2>Recommendations</h2><ul>{recommendations}</ul></section>"
    return "\n".join(
        [
            "<!doctype html>",
            '<html lang="zh-CN">',
            "<head>",
            '<meta charset="utf-8">',
            '<meta name="viewport" content="width=device-width, initial-scale=1">',
            '<link rel="icon" href="data:,">',
            f"<title>{html_escape(report.get('title', 'MiniGPT readability report'))}</title>",
            _style(),
            "</head>",
            "<body>",
            f"<header><h1>{html_escape(report.get('title', 'MiniGPT readability report'))}</h1><p>{html_escape(report.get('description', 'Late-stage maintenance report for keeping AI governance artifacts readable.'))}</p></header>",
            f"<section class=\"stats\">{stat_html}</section>",
            f"<section><h2>{html_escape(row_title)}</h2>{table_html}</section>",
            recommendations,
            "<footer>Generated by MiniGPT readability maintenance tooling.</footer>",
            "</body>",
            "</html>",
        ]
    )


def write_readability_outputs(
    report: dict[str, Any],
    out_dir: str | Path,
    *,
    stem: str,
    row_title: str = "Rows",
    row_key: str = "rows",
) -> dict[str, str]:
    return write_output_bundle(
        out_dir,
        {
            "json": f"{stem}.json",
            "csv": f"{stem}.csv",
            "text": f"{stem}.txt",
            "markdown": f"{stem}.md",
            "html": f"{stem}.html",
        },
        {
            "json": lambda path: write_json_payload(report, path),
            "csv": lambda path: write_readability_csv(report, path, row_key=row_key),
            "text": lambda path: path.write_text(render_readability_text(report), encoding="utf-8"),
            "markdown": lambda path: path.write_text(
                render_readability_markdown(report, row_title=row_title, row_key=row_key),
                encoding="utf-8",
            ),
            "html": lambda path: path.write_text(
                render_readability_html(report, row_title=row_title, row_key=row_key),
                encoding="utf-8",
            ),
        },
    )


def write_readability_csv(report: dict[str, Any], path: str | Path, *, row_key: str = "rows") -> None:
    rows = _rows(report, row_key)
    fieldnames = _fieldnames(report, rows)
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: csv_cell(row.get(field)) for field in fieldnames})


def _rows(report: dict[str, Any], row_key: str) -> list[dict[str, Any]]:
    value = report.get(row_key)
    if not isinstance(value, list):
        return []
    return [row for row in value if isinstance(row, dict)]


def _fieldnames(report: dict[str, Any], rows: list[dict[str, Any]]) -> list[str]:
    configured = string_list(report.get("csv_fieldnames"))
    if configured:
        return configured
    keys: list[str] = []
    for row in rows:
        for key in row:
            if key not in keys:
                keys.append(key)
    return keys or ["status"]


def _display(value: Any) -> str:
    if isinstance(value, list):
        return ", ".join(str(item) for item in value)
    if isinstance(value, dict):
        return ", ".join(f"{key}={item}" for key, item in value.items())
    return "" if value is None else str(value)


def _stat(label: str, value: Any) -> str:
    return f'<article class="stat"><span>{html_escape(label)}</span><strong>{html_escape(value)}</strong></article>'


def _style() -> str:
    return """
<style>
:root { color-scheme: light; font-family: Arial, "Microsoft YaHei", sans-serif; color: #172026; background: #f6f8fa; }
body { margin: 0; padding: 24px; }
header, section, footer { max-width: 1120px; margin: 0 auto 18px; }
header { padding: 18px 0 8px; border-bottom: 3px solid #2f6f8f; }
h1 { margin: 0 0 8px; font-size: 28px; letter-spacing: 0; }
h2 { margin: 0 0 10px; font-size: 18px; letter-spacing: 0; }
p { margin: 0 0 10px; line-height: 1.5; }
.stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 10px; background: transparent; border: 0; padding: 0; }
.stat { background: #fff; border: 1px solid #d7dee5; border-radius: 8px; padding: 12px; min-height: 64px; }
.stat span { display: block; color: #5c6b73; font-size: 12px; margin-bottom: 8px; }
.stat strong { display: block; font-size: 18px; overflow-wrap: anywhere; }
section { background: #fff; border: 1px solid #d7dee5; border-radius: 8px; padding: 16px; }
table { width: 100%; border-collapse: collapse; table-layout: fixed; }
th, td { padding: 9px; border-bottom: 1px solid #e5e9ef; text-align: left; vertical-align: top; overflow-wrap: anywhere; }
th { background: #eef3f6; }
ul { margin: 0; padding-left: 20px; }
li { margin: 6px 0; }
.muted { color: #687782; }
footer { color: #687782; font-size: 12px; }
</style>
""".strip()


__all__ = [
    "render_readability_html",
    "render_readability_markdown",
    "render_readability_text",
    "write_readability_csv",
    "write_readability_outputs",
]
