from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any

from minigpt.registry_leaderboards import (
    benchmark_rubric_leaderboard_html,
    loss_leaderboard_html,
    pair_delta_leaderboard_html,
    release_readiness_delta_leaderboard_html,
)
from minigpt.registry_render_helpers import (
    registry_controls,
    registry_run_row,
    registry_script,
    registry_stats,
    registry_style,
    stat_card,
)


def render_registry_html(
    registry: dict[str, Any],
    *,
    title: str = "MiniGPT run registry",
    base_dir: str | Path | None = None,
) -> str:
    runs = list(registry.get("runs", []))
    loss_leaderboard = registry.get("loss_leaderboard", [])
    stats = registry_stats(registry)
    rows = [registry_run_row(run, base_dir) for run in runs if isinstance(run, dict)]
    return "\n".join(
        [
            "<!doctype html>",
            '<html lang="zh-CN">',
            "<head>",
            '<meta charset="utf-8">',
            '<meta name="viewport" content="width=device-width, initial-scale=1">',
            '<link rel="icon" href="data:,">',
            f"<title>{_e(title)}</title>",
            registry_style(),
            "</head>",
            "<body>",
            f"<header><h1>{_e(title)}</h1><p>Experiment index generated from MiniGPT run directories.</p></header>",
            '<section class="stats">' + "".join(stat_card(label, value) for label, value in stats) + "</section>",
            registry_controls(runs),
            '<section class="panel">',
            "<h2>Runs</h2>",
            '<table id="registry-table">',
            "<thead><tr><th>Run</th><th>Rank</th><th>Best Val</th><th>Params</th><th>Git</th><th>Data</th><th>Quality</th><th>Eval</th><th>Gen Quality</th><th>Rubric</th><th>Pair Reports</th><th>Release Readiness</th><th>Artifacts</th><th>Notes</th><th>Links</th></tr></thead>",
            '<tbody id="registry-rows">',
            "".join(rows),
            "</tbody>",
            "</table>",
            "</section>",
            loss_leaderboard_html(loss_leaderboard),
            benchmark_rubric_leaderboard_html(registry.get("benchmark_rubric_leaderboard", [])),
            pair_delta_leaderboard_html(registry.get("pair_delta_leaderboard", []), base_dir),
            release_readiness_delta_leaderboard_html(registry.get("release_readiness_delta_leaderboard", []), base_dir),
            '<section class="panel">',
            "<h2>Dataset Fingerprints</h2>",
            "<pre>" + _e(json.dumps(registry.get("dataset_fingerprints", []), ensure_ascii=False, indent=2)) + "</pre>",
            "</section>",
            '<section class="panel">',
            "<h2>Dataset Snapshot Summary</h2>",
            "<pre>" + _e(json.dumps(registry.get("dataset_snapshot_summary", {}), ensure_ascii=False, indent=2)) + "</pre>",
            "</section>",
            "<footer>Generated by MiniGPT registry exporter.</footer>",
            registry_script(),
            "</body>",
            "</html>",
        ]
    )


def write_registry_json(registry: dict[str, Any], path: str | Path) -> None:
    from minigpt.registry_artifacts import write_registry_json as _write_registry_json

    _write_registry_json(registry, path)


def write_registry_csv(registry: dict[str, Any], path: str | Path) -> None:
    from minigpt.registry_artifacts import write_registry_csv as _write_registry_csv

    _write_registry_csv(registry, path)


def write_registry_svg(registry: dict[str, Any], path: str | Path) -> None:
    from minigpt.registry_artifacts import write_registry_svg as _write_registry_svg

    _write_registry_svg(registry, path)


def write_registry_html(registry: dict[str, Any], path: str | Path, title: str = "MiniGPT run registry") -> None:
    from minigpt.registry_artifacts import write_registry_html as _write_registry_html

    _write_registry_html(registry, path, title=title)


def write_registry_outputs(registry: dict[str, Any], out_dir: str | Path) -> dict[str, str]:
    from minigpt.registry_artifacts import write_registry_outputs as _write_registry_outputs

    return _write_registry_outputs(registry, out_dir)


def _e(value: Any) -> str:
    return html.escape("" if value is None else str(value), quote=True)
