from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from minigpt.report_utils import (
    as_dict as _dict,
    html_escape as _e,
    list_of_dicts as _list_of_dicts,
    write_json_payload,
)


def write_release_bundle_json(bundle: dict[str, Any], path: str | Path) -> None:
    write_json_payload(bundle, path)


def render_release_bundle_markdown(bundle: dict[str, Any]) -> str:
    summary = _dict(bundle.get("summary"))
    lines = [
        f"# {bundle.get('title', 'MiniGPT release bundle')}",
        "",
        f"- Release: `{bundle.get('release_name')}`",
        f"- Generated: `{bundle.get('generated_at')}`",
        "",
        "## Summary",
        "",
        *_markdown_table(
            [
                ("Release status", summary.get("release_status")),
                ("Audit status", summary.get("audit_status")),
                ("Audit score", summary.get("audit_score_percent")),
                ("Run count", summary.get("run_count")),
                ("Best run", summary.get("best_run_name")),
                ("Best val loss", _fmt(summary.get("best_val_loss"))),
                ("Ready runs", summary.get("ready_runs")),
                ("Request history status", summary.get("request_history_status")),
                ("CI workflow status", summary.get("ci_workflow_status")),
                ("CI workflow failed checks", summary.get("ci_workflow_failed_checks")),
                ("Evidence artifacts", summary.get("available_artifacts")),
            ]
        ),
        "",
        "## Inputs",
        "",
        *_markdown_table([(key, value) for key, value in _dict(bundle.get("inputs")).items()]),
        "",
        "## Top Runs",
        "",
        *_run_table(_list_of_dicts(bundle.get("top_runs"))),
        "",
        "## Audit Checks",
        "",
        "| Status | Check | Detail |",
        "| --- | --- | --- |",
    ]
    for check in _list_of_dicts(bundle.get("audit_checks")):
        lines.append(f"| {_md(check.get('status'))} | {_md(check.get('title'))} | {_md(check.get('detail'))} |")
    lines.extend(["", "## Evidence Artifacts", ""])
    lines.extend(_artifact_lines(_list_of_dicts(bundle.get("artifacts"))))
    lines.extend(["", "## Recommendations", ""])
    lines.extend(f"- {item}" for item in _string_list(bundle.get("recommendations")))
    warnings = _string_list(bundle.get("warnings"))
    if warnings:
        lines.extend(["", "## Warnings", ""])
        lines.extend(f"- {item}" for item in warnings)
    return "\n".join(lines).rstrip() + "\n"


def write_release_bundle_markdown(bundle: dict[str, Any], path: str | Path) -> None:
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_release_bundle_markdown(bundle), encoding="utf-8")


def render_release_bundle_html(bundle: dict[str, Any], *, base_dir: str | Path | None = None) -> str:
    summary = _dict(bundle.get("summary"))
    stats = [
        ("Release", summary.get("release_status")),
        ("Audit", summary.get("audit_status")),
        ("Score", f"{summary.get('audit_score_percent')}%"),
        ("Runs", summary.get("run_count")),
        ("Best run", summary.get("best_run_name")),
        ("Ready", summary.get("ready_runs")),
        ("Req history", summary.get("request_history_status")),
        ("CI workflow", summary.get("ci_workflow_status")),
        ("Artifacts", summary.get("available_artifacts")),
        ("Generated", bundle.get("generated_at")),
    ]
    return "\n".join(
        [
            "<!doctype html>",
            '<html lang="zh-CN">',
            "<head>",
            '<meta charset="utf-8">',
            '<meta name="viewport" content="width=device-width, initial-scale=1">',
            '<link rel="icon" href="data:,">',
            f"<title>{_e(bundle.get('title', 'MiniGPT release bundle'))}</title>",
            _style(),
            "</head>",
            "<body>",
            f"<header><h1>{_e(bundle.get('title', 'MiniGPT release bundle'))}</h1><p>{_e(bundle.get('release_name'))}</p></header>",
            '<section class="stats">' + "".join(_stat(label, value) for label, value in stats) + "</section>",
            _key_value_section("Inputs", _dict(bundle.get("inputs"))),
            _run_section("Top Runs", _list_of_dicts(bundle.get("top_runs")), base_dir),
            _check_section(_list_of_dicts(bundle.get("audit_checks"))),
            _artifact_section(_list_of_dicts(bundle.get("artifacts")), base_dir),
            _list_section("Recommendations", bundle.get("recommendations")),
            _list_section("Warnings", bundle.get("warnings"), hide_empty=True),
            "<footer>Generated by MiniGPT release bundle exporter.</footer>",
            "</body>",
            "</html>",
        ]
    )


def write_release_bundle_html(bundle: dict[str, Any], path: str | Path) -> None:
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_release_bundle_html(bundle, base_dir=out_path.parent), encoding="utf-8")


def write_release_bundle_outputs(bundle: dict[str, Any], out_dir: str | Path) -> dict[str, str]:
    root = Path(out_dir)
    root.mkdir(parents=True, exist_ok=True)
    paths = {
        "json": root / "release_bundle.json",
        "markdown": root / "release_bundle.md",
        "html": root / "release_bundle.html",
    }
    write_release_bundle_json(bundle, paths["json"])
    write_release_bundle_markdown(bundle, paths["markdown"])
    write_release_bundle_html(bundle, paths["html"])
    return {key: str(value) for key, value in paths.items()}


def _artifact_lines(artifacts: list[dict[str, Any]]) -> list[str]:
    lines = []
    for artifact in artifacts:
        state = "yes" if artifact.get("exists") else "no"
        lines.append(f"- `{artifact.get('path')}`: {state}, {artifact.get('kind')}, {_fmt_bytes(artifact.get('size_bytes'))}")
    return lines


def _run_table(runs: list[dict[str, Any]]) -> list[str]:
    lines = ["| Rank | Run | Status | Best Val | Delta | Quality | Eval |", "| --- | --- | --- | --- | --- | --- | --- |"]
    for run in runs:
        lines.append(
            "| "
            + " | ".join(
                [
                    _md(_rank_label(run.get("best_val_loss_rank"))),
                    _md(run.get("name")),
                    _md(run.get("status")),
                    _md(_fmt(run.get("best_val_loss"))),
                    _md(_fmt_delta(run.get("best_val_loss_delta"))),
                    _md(run.get("dataset_quality")),
                    _md(run.get("eval_suite_cases")),
                ]
            )
            + " |"
        )
    return lines


def _key_value_section(title: str, payload: dict[str, Any]) -> str:
    rows = "".join(f"<tr><th>{_e(key)}</th><td>{_e(_fmt_any(value))}</td></tr>" for key, value in payload.items())
    return f'<section class="panel"><h2>{_e(title)}</h2><table>{rows}</table></section>'


def _run_section(title: str, runs: list[dict[str, Any]], base_dir: str | Path | None) -> str:
    rows = []
    for run in runs:
        card = run.get("experiment_card_html") or run.get("experiment_card_path")
        card_link = _path_link(card, base_dir, "card") if card else '<span class="muted">missing</span>'
        rows.append(
            "<tr>"
            f"<td>{_e(_rank_label(run.get('best_val_loss_rank')))}</td>"
            f"<td><strong>{_e(run.get('name'))}</strong><br><span>{_e(run.get('path'))}</span></td>"
            f"<td>{_e(run.get('status'))}</td>"
            f"<td>{_e(_fmt(run.get('best_val_loss')))}<br><span>{_e(_fmt_delta(run.get('best_val_loss_delta')))}</span></td>"
            f"<td>{_e(run.get('dataset_quality'))}</td>"
            f"<td>{_e(run.get('eval_suite_cases'))}</td>"
            f"<td>{card_link}</td>"
            "</tr>"
        )
    return f'<section class="panel"><h2>{_e(title)}</h2><table><thead><tr><th>Rank</th><th>Run</th><th>Status</th><th>Best Val</th><th>Quality</th><th>Eval</th><th>Card</th></tr></thead><tbody>' + "".join(rows) + "</tbody></table></section>"


def _check_section(checks: list[dict[str, Any]]) -> str:
    if not checks:
        return '<section class="panel"><h2>Audit Checks</h2><p class="muted">missing</p></section>'
    rows = []
    for check in checks:
        status = str(check.get("status") or "missing")
        rows.append(
            "<tr>"
            f'<td><span class="pill {status}">{_e(status)}</span></td>'
            f"<td><strong>{_e(check.get('title'))}</strong><br><span>{_e(check.get('id'))}</span></td>"
            f"<td>{_e(check.get('detail'))}</td>"
            "</tr>"
        )
    return '<section class="panel"><h2>Audit Checks</h2><table><thead><tr><th>Status</th><th>Check</th><th>Detail</th></tr></thead><tbody>' + "".join(rows) + "</tbody></table></section>"


def _artifact_section(artifacts: list[dict[str, Any]], base_dir: str | Path | None) -> str:
    rows = []
    for artifact in artifacts:
        path = artifact.get("path")
        label = _path_link(path, base_dir, artifact.get("title") or artifact.get("key")) if artifact.get("exists") else _e(path)
        rows.append(
            "<tr>"
            f"<td>{_e(artifact.get('key'))}</td>"
            f"<td>{label}<br><span>{_e(artifact.get('description'))}</span></td>"
            f"<td>{_e('yes' if artifact.get('exists') else 'no')}</td>"
            f"<td>{_e(artifact.get('kind'))}</td>"
            f"<td>{_e(_fmt_bytes(artifact.get('size_bytes')))}</td>"
            "</tr>"
        )
    return '<section class="panel"><h2>Evidence Artifacts</h2><table><thead><tr><th>Key</th><th>Artifact</th><th>Exists</th><th>Kind</th><th>Size</th></tr></thead><tbody>' + "".join(rows) + "</tbody></table></section>"


def _list_section(title: str, values: Any, hide_empty: bool = False) -> str:
    items = _string_list(values)
    if hide_empty and not items:
        return ""
    if not items:
        items = ["missing"]
    return f'<section class="panel"><h2>{_e(title)}</h2><ul>' + "".join(f"<li>{_e(item)}</li>" for item in items) + "</ul></section>"


def _stat(label: str, value: Any) -> str:
    return '<div class="card">' + f'<div class="label">{_e(label)}</div><div class="value">{_e(_fmt_any(value))}</div>' + "</div>"


def _path_link(path: Any, base_dir: str | Path | None, label: Any) -> str:
    if path is None:
        return '<span class="muted">missing</span>'
    href = str(path)
    if base_dir is not None:
        try:
            href = Path(os.path.relpath(Path(str(path)), Path(base_dir))).as_posix()
        except ValueError:
            href = Path(str(path)).as_posix()
    return f'<a href="{_e(href)}">{_e(label)}</a>'


def _style() -> str:
    return """<style>
:root { --ink:#111827; --muted:#4b5563; --line:#d8dee9; --page:#f7f7f2; --panel:#fff; --blue:#2563eb; --green:#047857; --amber:#b45309; --red:#b91c1c; }
* { box-sizing:border-box; }
body { margin:0; background:var(--page); color:var(--ink); font-family:Arial, "Microsoft YaHei", sans-serif; line-height:1.45; }
header { padding:28px 32px 18px; background:#fff; border-bottom:1px solid var(--line); }
h1 { margin:0 0 8px; font-size:28px; letter-spacing:0; }
h2 { margin:0 0 12px; font-size:18px; }
span, .muted { color:var(--muted); }
.stats { display:grid; grid-template-columns:repeat(auto-fit, minmax(150px, 1fr)); gap:12px; padding:18px 32px 4px; }
.card, .panel { background:var(--panel); border:1px solid var(--line); border-radius:8px; }
.card { padding:14px; min-height:82px; }
.label { color:var(--muted); font-size:12px; text-transform:uppercase; }
.value { margin-top:6px; font-size:20px; font-weight:700; overflow-wrap:anywhere; }
.panel { margin:18px 32px; padding:16px; overflow-x:auto; }
table { width:100%; border-collapse:collapse; min-width:920px; }
th, td { padding:8px; border-bottom:1px solid var(--line); text-align:left; vertical-align:top; }
th { color:var(--muted); font-size:12px; text-transform:uppercase; }
a { color:var(--blue); font-weight:700; text-decoration:none; }
.pill { display:inline-block; min-width:54px; padding:3px 8px; border-radius:999px; color:#fff; text-align:center; font-size:12px; font-weight:700; }
.pill.pass { background:var(--green); }
.pill.warn { background:var(--amber); }
.pill.fail { background:var(--red); }
footer { padding:20px 32px 34px; color:var(--muted); font-size:13px; }
@media (max-width:760px) { header, .stats { padding-left:16px; padding-right:16px; } .panel { margin-left:16px; margin-right:16px; } }
</style>"""


def _markdown_table(rows: list[tuple[str, Any]]) -> list[str]:
    lines = ["| Field | Value |", "| --- | --- |"]
    for key, value in rows:
        lines.append(f"| {_md(key)} | {_md(value)} |")
    return lines


def _string_list(value: Any) -> list[str]:
    return [str(item) for item in value if str(item).strip()] if isinstance(value, list) else []


def _fmt(value: Any) -> str:
    if value is None:
        return "missing"
    if isinstance(value, float):
        return f"{value:.5g}"
    return str(value)


def _fmt_delta(value: Any) -> str:
    if value is None or value == "":
        return "missing"
    return f"{float(value):+.5g}"


def _fmt_any(value: Any) -> str:
    if isinstance(value, float):
        return f"{value:.5g}"
    return "missing" if value is None else str(value)


def _fmt_bytes(value: Any) -> str:
    if value is None:
        return "missing"
    return f"{int(value):,} bytes"


def _rank_label(value: Any) -> str:
    if value is None or value == "":
        return "unranked"
    return f"#{int(value)}"


def _md(value: Any) -> str:
    return _fmt_any(value).replace("|", "\\|").replace("\n", " ")


__all__ = [
    "render_release_bundle_html",
    "render_release_bundle_markdown",
    "write_release_bundle_html",
    "write_release_bundle_json",
    "write_release_bundle_markdown",
    "write_release_bundle_outputs",
]
