from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from minigpt.report_utils import (
    as_dict as _dict,
    html_escape as _e,
    list_of_dicts as _list_of_dicts,
    write_json_payload,
)


def write_release_gate_json(gate: dict[str, Any], path: str | Path) -> None:
    write_json_payload(gate, path)


def render_release_gate_markdown(gate: dict[str, Any]) -> str:
    summary = _dict(gate.get("summary"))
    policy = _dict(gate.get("policy"))
    lines = [
        f"# {gate.get('title', 'MiniGPT release gate')}",
        "",
        f"- Release: `{gate.get('release_name')}`",
        f"- Generated: `{gate.get('generated_at')}`",
        f"- Bundle: `{gate.get('bundle_path')}`",
        "",
        "## Summary",
        "",
        *_markdown_table(
            [
                ("Gate status", summary.get("gate_status")),
                ("Decision", summary.get("decision")),
                ("Release status", summary.get("release_status")),
                ("Audit status", summary.get("audit_status")),
                ("Audit score", summary.get("audit_score_percent")),
                ("Ready runs", summary.get("ready_runs")),
                ("Missing artifacts", summary.get("missing_artifacts")),
                ("Pass checks", summary.get("pass_count")),
                ("Warn checks", summary.get("warn_count")),
                ("Fail checks", summary.get("fail_count")),
            ]
        ),
        "",
        "## Policy",
        "",
        *_markdown_table([(key, value) for key, value in policy.items()]),
        "",
        "## Checks",
        "",
        "| Status | Check | Detail |",
        "| --- | --- | --- |",
    ]
    for check in _list_of_dicts(gate.get("checks")):
        lines.append(f"| {_md(check.get('status'))} | {_md(check.get('title'))} | {_md(check.get('detail'))} |")
    lines.extend(["", "## Recommendations", ""])
    lines.extend(f"- {item}" for item in _string_list(gate.get("recommendations")))
    bundle_recommendations = _string_list(gate.get("bundle_recommendations"))
    if bundle_recommendations:
        lines.extend(["", "## Bundle Recommendations", ""])
        lines.extend(f"- {item}" for item in bundle_recommendations)
    warnings = _string_list(gate.get("warnings"))
    if warnings:
        lines.extend(["", "## Bundle Warnings", ""])
        lines.extend(f"- {item}" for item in warnings)
    return "\n".join(lines).rstrip() + "\n"


def write_release_gate_markdown(gate: dict[str, Any], path: str | Path) -> None:
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_release_gate_markdown(gate), encoding="utf-8")


def render_release_gate_html(gate: dict[str, Any]) -> str:
    summary = _dict(gate.get("summary"))
    stats = [
        ("Gate", summary.get("gate_status")),
        ("Decision", summary.get("decision")),
        ("Release", summary.get("release_status")),
        ("Audit", summary.get("audit_status")),
        ("Score", _score_label(summary.get("audit_score_percent"))),
        ("Ready", summary.get("ready_runs")),
        ("Missing", summary.get("missing_artifacts")),
        ("Generated", gate.get("generated_at")),
    ]
    return "\n".join(
        [
            "<!doctype html>",
            '<html lang="zh-CN">',
            "<head>",
            '<meta charset="utf-8">',
            '<meta name="viewport" content="width=device-width, initial-scale=1">',
            '<link rel="icon" href="data:,">',
            f"<title>{_e(gate.get('title', 'MiniGPT release gate'))}</title>",
            _style(),
            "</head>",
            "<body>",
            f"<header><h1>{_e(gate.get('title', 'MiniGPT release gate'))}</h1><p>{_e(gate.get('release_name'))}</p></header>",
            '<section class="stats">' + "".join(_stat(label, value) for label, value in stats) + "</section>",
            _key_value_section("Policy", _dict(gate.get("policy"))),
            _check_section(_list_of_dicts(gate.get("checks"))),
            _list_section("Recommendations", gate.get("recommendations")),
            _list_section("Bundle Recommendations", gate.get("bundle_recommendations"), hide_empty=True),
            _list_section("Bundle Warnings", gate.get("warnings"), hide_empty=True),
            "<footer>Generated by MiniGPT release gate.</footer>",
            "</body>",
            "</html>",
        ]
    )


def write_release_gate_html(gate: dict[str, Any], path: str | Path) -> None:
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_release_gate_html(gate), encoding="utf-8")


def write_release_gate_outputs(gate: dict[str, Any], out_dir: str | Path) -> dict[str, str]:
    root = Path(out_dir)
    root.mkdir(parents=True, exist_ok=True)
    paths = {
        "json": root / "gate_report.json",
        "markdown": root / "gate_report.md",
        "html": root / "gate_report.html",
    }
    write_release_gate_json(gate, paths["json"])
    write_release_gate_markdown(gate, paths["markdown"])
    write_release_gate_html(gate, paths["html"])
    return {key: str(value) for key, value in paths.items()}


def _key_value_section(title: str, payload: dict[str, Any]) -> str:
    rows = "".join(f"<tr><th>{_e(key)}</th><td>{_e(_fmt_any(value))}</td></tr>" for key, value in payload.items())
    return f'<section class="panel"><h2>{_e(title)}</h2><table>{rows}</table></section>'


def _check_section(checks: list[dict[str, Any]]) -> str:
    rows = []
    for check in checks:
        status = str(check.get("status") or "missing")
        rows.append(
            "<tr>"
            f'<td><span class="pill {status}">{_e(status)}</span></td>'
            f"<td><strong>{_e(check.get('title'))}</strong><br><span>{_e(check.get('id'))}</span></td>"
            f"<td>{_e(check.get('detail'))}</td>"
            "</tr>"
        )
    return '<section class="panel"><h2>Checks</h2><table><thead><tr><th>Status</th><th>Check</th><th>Detail</th></tr></thead><tbody>' + "".join(rows) + "</tbody></table></section>"


def _list_section(title: str, values: Any, hide_empty: bool = False) -> str:
    items = _string_list(values)
    if hide_empty and not items:
        return ""
    if not items:
        items = ["missing"]
    return f'<section class="panel"><h2>{_e(title)}</h2><ul>' + "".join(f"<li>{_e(item)}</li>" for item in items) + "</ul></section>"


def _stat(label: str, value: Any) -> str:
    return '<div class="card">' + f'<div class="label">{_e(label)}</div><div class="value">{_e(_fmt_any(value))}</div>' + "</div>"


def _style() -> str:
    return """<style>
:root { --ink:#101828; --muted:#4b5563; --line:#d7dce5; --page:#f6f8fb; --panel:#fff; --blue:#1d4ed8; --green:#047857; --amber:#b45309; --red:#b91c1c; }
* { box-sizing:border-box; }
body { margin:0; background:var(--page); color:var(--ink); font-family:Arial, "Microsoft YaHei", sans-serif; line-height:1.45; }
header { padding:28px 32px 18px; background:#fff; border-bottom:1px solid var(--line); }
h1 { margin:0 0 8px; font-size:28px; letter-spacing:0; }
h2 { margin:0 0 12px; font-size:18px; }
span, .muted { color:var(--muted); }
.stats { display:grid; grid-template-columns:repeat(auto-fit, minmax(150px, 1fr)); gap:12px; padding:18px 32px 4px; }
.card, .panel { background:var(--panel); border:1px solid var(--line); border-radius:8px; }
.card { padding:14px; min-height:82px; }
.label { color:var(--muted); font-size:12px; text-transform:uppercase; }
.value { margin-top:6px; font-size:20px; font-weight:700; overflow-wrap:anywhere; }
.panel { margin:18px 32px; padding:16px; overflow-x:auto; }
table { width:100%; border-collapse:collapse; min-width:820px; }
th, td { padding:8px; border-bottom:1px solid var(--line); text-align:left; vertical-align:top; }
th { color:var(--muted); font-size:12px; text-transform:uppercase; }
.pill { display:inline-block; min-width:54px; padding:3px 8px; border-radius:999px; color:#fff; text-align:center; font-size:12px; font-weight:700; }
.pill.pass { background:var(--green); }
.pill.warn { background:var(--amber); }
.pill.fail { background:var(--red); }
footer { padding:20px 32px 34px; color:var(--muted); font-size:13px; }
@media (max-width:760px) { header, .stats { padding-left:16px; padding-right:16px; } .panel { margin-left:16px; margin-right:16px; } }
</style>"""


def _markdown_table(rows: list[tuple[str, Any]]) -> list[str]:
    lines = ["| Field | Value |", "| --- | --- |"]
    for key, value in rows:
        lines.append(f"| {_md(key)} | {_md(value)} |")
    return lines


def _string_list(value: Any) -> list[str]:
    return [str(item) for item in value if str(item).strip()] if isinstance(value, list) else []


def _number(value: Any) -> float | None:
    try:
        if value is None or value == "":
            return None
        return float(value)
    except (TypeError, ValueError):
        return None


def _score_label(value: Any) -> str:
    number = _number(value)
    if number is None:
        return "missing"
    return f"{number:g}%"


def _fmt_any(value: Any) -> str:
    if isinstance(value, float):
        return f"{value:.5g}"
    if isinstance(value, (dict, list)):
        return json.dumps(value, ensure_ascii=False, sort_keys=True)
    return "missing" if value is None else str(value)


def _md(value: Any) -> str:
    return _fmt_any(value).replace("|", "\\|").replace("\n", " ")
