from __future__ import annotations

from pathlib import Path
from typing import Any

from minigpt.report_utils import (
    as_dict as _dict,
    html_escape as _e,
    list_of_dicts as _list_of_dicts,
    write_json_payload,
)


def write_release_readiness_json(report: dict[str, Any], path: str | Path) -> None:
    write_json_payload(report, path)


def render_release_readiness_markdown(report: dict[str, Any]) -> str:
    summary = _dict(report.get("summary"))
    lines = [
        f"# {report.get('title', 'MiniGPT release readiness dashboard')}",
        "",
        f"- Generated: `{report.get('generated_at')}`",
        f"- Bundle: `{report.get('bundle_path')}`",
        "",
        "## Summary",
        "",
        *_markdown_table(
            [
                ("Readiness status", summary.get("readiness_status")),
                ("Decision", summary.get("decision")),
                ("Release", summary.get("release_name")),
                ("Gate", summary.get("gate_status")),
                ("Audit", summary.get("audit_status")),
                ("Audit score", summary.get("audit_score_percent")),
                ("CI workflow", summary.get("ci_workflow_status")),
                ("Request history", summary.get("request_history_status")),
                ("Maturity", summary.get("maturity_status")),
                ("Ready runs", summary.get("ready_runs")),
                ("Missing artifacts", summary.get("missing_artifacts")),
            ]
        ),
        "",
        "## Panels",
        "",
        "| Status | Panel | Detail | Source |",
        "| --- | --- | --- | --- |",
    ]
    for panel in _list_of_dicts(report.get("panels")):
        lines.append(f"| {_md(panel.get('status'))} | {_md(panel.get('title'))} | {_md(panel.get('detail'))} | {_md(panel.get('source_path'))} |")
    lines.extend(["", "## Actions", ""])
    lines.extend(f"- {item}" for item in _string_list(report.get("actions")))
    lines.extend(["", "## Evidence", ""])
    lines.extend(_evidence_lines(_list_of_dicts(report.get("evidence"))))
    warnings = _string_list(report.get("warnings"))
    if warnings:
        lines.extend(["", "## Warnings", ""])
        lines.extend(f"- {item}" for item in warnings)
    return "\n".join(lines).rstrip() + "\n"


def write_release_readiness_markdown(report: dict[str, Any], path: str | Path) -> None:
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_release_readiness_markdown(report), encoding="utf-8")


def render_release_readiness_html(report: dict[str, Any]) -> str:
    summary = _dict(report.get("summary"))
    stats = [
        ("Readiness", summary.get("readiness_status")),
        ("Decision", summary.get("decision")),
        ("Release", summary.get("release_status")),
        ("Gate", summary.get("gate_status")),
        ("Audit", summary.get("audit_status")),
        ("Score", _fmt(summary.get("audit_score_percent"))),
        ("CI workflow", summary.get("ci_workflow_status")),
        ("Requests", summary.get("request_history_status")),
        ("Maturity", summary.get("maturity_status")),
    ]
    return "\n".join(
        [
            "<!doctype html>",
            '<html lang="zh-CN">',
            "<head>",
            '<meta charset="utf-8">',
            '<meta name="viewport" content="width=device-width, initial-scale=1">',
            '<link rel="icon" href="data:,">',
            f"<title>{_e(report.get('title', 'MiniGPT release readiness dashboard'))}</title>",
            _style(),
            "</head>",
            "<body>",
            f"<header><h1>{_e(report.get('title', 'MiniGPT release readiness dashboard'))}</h1><p>{_e(report.get('bundle_path'))}</p></header>",
            '<section class="stats">' + "".join(_stat(label, value) for label, value in stats) + "</section>",
            _panel_section(_list_of_dicts(report.get("panels"))),
            _list_section("Actions", report.get("actions")),
            _evidence_section(_list_of_dicts(report.get("evidence"))),
            _list_section("Warnings", report.get("warnings"), hide_empty=True),
            "<footer>Generated by MiniGPT release readiness dashboard.</footer>",
            "</body>",
            "</html>",
        ]
    )


def write_release_readiness_html(report: dict[str, Any], path: str | Path) -> None:
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_release_readiness_html(report), encoding="utf-8")


def write_release_readiness_outputs(report: dict[str, Any], out_dir: str | Path) -> dict[str, str]:
    root = Path(out_dir)
    root.mkdir(parents=True, exist_ok=True)
    paths = {
        "json": root / "release_readiness.json",
        "markdown": root / "release_readiness.md",
        "html": root / "release_readiness.html",
    }
    write_release_readiness_json(report, paths["json"])
    write_release_readiness_markdown(report, paths["markdown"])
    write_release_readiness_html(report, paths["html"])
    return {key: str(value) for key, value in paths.items()}


def _panel_section(panels: list[dict[str, Any]]) -> str:
    cards = []
    for panel in panels:
        status = str(panel.get("status") or "warn")
        cards.append(
            '<article class="panel-card">'
            f'<span class="pill {status}">{_e(status)}</span>'
            f"<h2>{_e(panel.get('title'))}</h2>"
            f"<p>{_e(panel.get('detail'))}</p>"
            f"<code>{_e(panel.get('source_path') or 'missing')}</code>"
            "</article>"
        )
    return '<section class="panel-grid">' + "".join(cards) + "</section>"


def _evidence_section(items: list[dict[str, Any]]) -> str:
    if not items:
        return '<section class="panel"><h2>Evidence</h2><p class="muted">missing</p></section>'
    rows = []
    for item in items:
        exists = "yes" if item.get("exists") else "no"
        rows.append(
            "<tr>"
            f"<td>{_e(item.get('key'))}</td>"
            f"<td><strong>{_e(item.get('title'))}</strong><br><span>{_e(item.get('path'))}</span></td>"
            f"<td>{_e(exists)}</td>"
            f"<td>{_e(item.get('kind'))}</td>"
            f"<td>{_e(_fmt_bytes(item.get('size_bytes')))}</td>"
            "</tr>"
        )
    return '<section class="panel"><h2>Evidence</h2><table><thead><tr><th>Key</th><th>Artifact</th><th>Exists</th><th>Kind</th><th>Size</th></tr></thead><tbody>' + "".join(rows) + "</tbody></table></section>"


def _list_section(title: str, values: Any, hide_empty: bool = False) -> str:
    items = _string_list(values)
    if hide_empty and not items:
        return ""
    if not items:
        items = ["missing"]
    return f'<section class="panel"><h2>{_e(title)}</h2><ul>' + "".join(f"<li>{_e(item)}</li>" for item in items) + "</ul></section>"


def _stat(label: str, value: Any) -> str:
    return '<div class="card">' + f'<div class="label">{_e(label)}</div><div class="value">{_e(_fmt(value))}</div>' + "</div>"


def _style() -> str:
    return """<style>
:root { --ink:#17202a; --muted:#566170; --line:#d5dce6; --page:#f6f7f3; --panel:#fff; --green:#047857; --amber:#b45309; --red:#b91c1c; --blue:#1f5f74; }
* { box-sizing:border-box; }
body { margin:0; background:var(--page); color:var(--ink); font-family:Arial, "Microsoft YaHei", sans-serif; line-height:1.45; }
header { padding:28px 32px 18px; background:#fff; border-bottom:1px solid var(--line); }
h1 { margin:0 0 8px; font-size:28px; letter-spacing:0; }
h2 { margin:8px 0 8px; font-size:18px; }
span, .muted { color:var(--muted); }
code { display:block; margin-top:8px; color:var(--muted); overflow-wrap:anywhere; }
.stats, .panel-grid { display:grid; gap:12px; padding:18px 32px 4px; }
.stats { grid-template-columns:repeat(auto-fit, minmax(145px, 1fr)); }
.panel-grid { grid-template-columns:repeat(auto-fit, minmax(260px, 1fr)); }
.card, .panel, .panel-card { background:var(--panel); border:1px solid var(--line); border-radius:8px; }
.card { padding:14px; min-height:82px; }
.panel-card { padding:16px; min-height:150px; }
.label { color:var(--muted); font-size:12px; text-transform:uppercase; }
.value { margin-top:6px; font-size:20px; font-weight:700; overflow-wrap:anywhere; }
.panel { margin:18px 32px; padding:16px; overflow-x:auto; }
table { width:100%; border-collapse:collapse; min-width:920px; }
th, td { padding:8px; border-bottom:1px solid var(--line); text-align:left; vertical-align:top; }
th { color:var(--muted); font-size:12px; text-transform:uppercase; }
.pill { display:inline-block; min-width:54px; padding:3px 8px; border-radius:999px; color:#fff; text-align:center; font-size:12px; font-weight:700; }
.pill.pass { background:var(--green); }
.pill.warn { background:var(--amber); }
.pill.fail { background:var(--red); }
footer { padding:20px 32px 34px; color:var(--muted); font-size:13px; }
@media (max-width:760px) { header, .stats, .panel-grid { padding-left:16px; padding-right:16px; } .panel { margin-left:16px; margin-right:16px; } }
</style>"""


def _markdown_table(rows: list[tuple[str, Any]]) -> list[str]:
    lines = ["| Field | Value |", "| --- | --- |"]
    lines.extend(f"| {_md(key)} | {_md(value)} |" for key, value in rows)
    return lines


def _evidence_lines(items: list[dict[str, Any]]) -> list[str]:
    if not items:
        return ["- missing"]
    return [
        f"- `{item.get('path')}`: {'yes' if item.get('exists') else 'no'}, {item.get('kind')}, {_fmt_bytes(item.get('size_bytes'))}"
        for item in items
    ]


def _fmt(value: Any) -> str:
    if value is None:
        return "missing"
    if isinstance(value, float):
        return f"{value:.5g}"
    return str(value)


def _fmt_bytes(value: Any) -> str:
    if value in {None, ""}:
        return "missing"
    size = int(value)
    if size < 1024:
        return f"{size} B"
    if size < 1024 * 1024:
        return f"{size / 1024:.1f} KB"
    return f"{size / (1024 * 1024):.1f} MB"


def _string_list(value: Any) -> list[str]:
    return [str(item) for item in value if str(item).strip()] if isinstance(value, list) else []


def _md(value: Any) -> str:
    return _fmt(value).replace("|", "\\|").replace("\n", " ")


__all__ = [
    "render_release_readiness_html",
    "render_release_readiness_markdown",
    "write_release_readiness_html",
    "write_release_readiness_json",
    "write_release_readiness_markdown",
    "write_release_readiness_outputs",
]
