from __future__ import annotations

import csv
from pathlib import Path
from typing import Any

from minigpt.report_utils import (
    as_dict as _dict,
    csv_cell as _csv_value,
    display_command as _display_command,
    html_escape as _e,
    list_of_dicts as _list_of_dicts,
    markdown_cell as _md,
    string_list as _string_list,
    write_json_payload,
)


def write_training_scale_gate_json(report: dict[str, Any], path: str | Path) -> None:
    write_json_payload(report, path)


def write_training_scale_gate_csv(report: dict[str, Any], path: str | Path) -> None:
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = ["code", "status", "message", "recommendation", "details"]
    with out_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for check in _list_of_dicts(report.get("checks")):
            writer.writerow(
                {
                    "code": check.get("code"),
                    "status": check.get("status"),
                    "message": check.get("message"),
                    "recommendation": check.get("recommendation"),
                    "details": _csv_value(check.get("details", {})),
                }
            )


def render_training_scale_gate_markdown(report: dict[str, Any]) -> str:
    summary = _dict(report.get("plan_summary"))
    lines = [
        f"# {report.get('title', 'MiniGPT training scale gate')}",
        "",
        f"- Generated: `{report.get('generated_at')}`",
        f"- Profile: `{report.get('profile')}`",
        f"- Status: `{report.get('overall_status')}`",
        f"- Plan: `{report.get('plan_path')}`",
        f"- Dataset: `{summary.get('dataset_name')}` / `{summary.get('version_prefix')}`",
        f"- Scale: `{summary.get('scale_tier')}`",
        f"- Characters: `{summary.get('char_count')}`",
        f"- Variants: `{summary.get('variant_count')}`",
        f"- Warnings: `{summary.get('warning_count')}`",
        "",
        "## Checks",
        "",
        "| Status | Code | Message | Recommendation |",
        "| --- | --- | --- | --- |",
    ]
    for check in _list_of_dicts(report.get("checks")):
        lines.append(
            "| "
            + " | ".join(
                [
                    _md(check.get("status")),
                    _md(check.get("code")),
                    _md(check.get("message")),
                    _md(check.get("recommendation")),
                ]
            )
            + " |"
        )
    lines.extend(["", "## Recommendations", ""])
    lines.extend(f"- {item}" for item in _string_list(report.get("recommendations")))
    batch = _dict(report.get("batch"))
    if batch.get("command"):
        lines.extend(["", "## Batch Command", "", f"`{_display_command(batch.get('command'))}`"])
    return "\n".join(lines).rstrip() + "\n"


def write_training_scale_gate_markdown(report: dict[str, Any], path: str | Path) -> None:
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_training_scale_gate_markdown(report), encoding="utf-8")


def render_training_scale_gate_html(report: dict[str, Any]) -> str:
    summary = _dict(report.get("plan_summary"))
    stats = [
        ("Status", report.get("overall_status")),
        ("Profile", report.get("profile")),
        ("Pass", report.get("pass_count")),
        ("Warn", report.get("warn_count")),
        ("Fail", report.get("fail_count")),
        ("Scale", summary.get("scale_tier")),
        ("Chars", summary.get("char_count")),
        ("Variants", summary.get("variant_count")),
    ]
    batch = _dict(report.get("batch"))
    return "\n".join(
        [
            "<!doctype html>",
            '<html lang="zh-CN">',
            "<head>",
            '<meta charset="utf-8">',
            '<meta name="viewport" content="width=device-width, initial-scale=1">',
            '<link rel="icon" href="data:,">',
            f"<title>{_e(report.get('title', 'MiniGPT training scale gate'))}</title>",
            _style(),
            "</head>",
            "<body>",
            f"<header><h1>{_e(report.get('title', 'MiniGPT training scale gate'))}</h1><p>{_e(summary.get('dataset_name'))} / {_e(summary.get('version_prefix'))}</p></header>",
            '<section class="stats">' + "".join(_card(label, value) for label, value in stats) + "</section>",
            _checks_table(report),
            _list_section("Recommendations", report.get("recommendations")),
            _batch_section(batch),
            "<footer>Generated by MiniGPT training scale gate.</footer>",
            "</body>",
            "</html>",
        ]
    )


def write_training_scale_gate_html(report: dict[str, Any], path: str | Path) -> None:
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_training_scale_gate_html(report), encoding="utf-8")


def write_training_scale_gate_outputs(report: dict[str, Any], out_dir: str | Path) -> dict[str, str]:
    root = Path(out_dir)
    root.mkdir(parents=True, exist_ok=True)
    paths = {
        "json": root / "training_scale_gate.json",
        "csv": root / "training_scale_gate.csv",
        "markdown": root / "training_scale_gate.md",
        "html": root / "training_scale_gate.html",
    }
    write_training_scale_gate_json(report, paths["json"])
    write_training_scale_gate_csv(report, paths["csv"])
    write_training_scale_gate_markdown(report, paths["markdown"])
    write_training_scale_gate_html(report, paths["html"])
    return {key: str(value) for key, value in paths.items()}


def _checks_table(report: dict[str, Any]) -> str:
    rows = []
    for check in _list_of_dicts(report.get("checks")):
        status = str(check.get("status") or "")
        rows.append(
            f'<tr class="{_e(status)}">'
            f"<td>{_e(status)}</td>"
            f"<td>{_e(check.get('code'))}</td>"
            f"<td>{_e(check.get('message'))}</td>"
            f"<td>{_e(check.get('recommendation'))}</td>"
            "</tr>"
        )
    return (
        '<section><h2>Checks</h2><div class="table-wrap"><table>'
        "<thead><tr><th>Status</th><th>Code</th><th>Message</th><th>Recommendation</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table></div></section>"
    )


def _batch_section(batch: dict[str, Any]) -> str:
    if not batch:
        return ""
    return (
        "<section><h2>Batch Handoff</h2>"
        f"<p><strong>Variants:</strong> {_e(batch.get('variants_path'))}</p>"
        f"<pre>{_e(_display_command(batch.get('command')))}</pre>"
        "</section>"
    )


def _list_section(title: str, items: Any) -> str:
    values = _string_list(items)
    if not values:
        return ""
    rows = "".join(f"<li>{_e(item)}</li>" for item in values)
    return f"<section><h2>{_e(title)}</h2><ul>{rows}</ul></section>"


def _style() -> str:
    return """<style>
:root { color-scheme: light; font-family: "Segoe UI", Arial, sans-serif; background: #f6f7f2; color: #172026; }
body { margin: 0; padding: 28px; }
header, section, footer { max-width: 1120px; margin: 0 auto 18px; }
header { border-bottom: 1px solid #d7dccf; padding-bottom: 18px; }
h1 { font-size: 30px; margin: 0 0 8px; letter-spacing: 0; }
h2 { font-size: 18px; margin: 0 0 12px; letter-spacing: 0; }
p { color: #4f5d52; }
.stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); gap: 10px; }
.card, section { background: #ffffff; border: 1px solid #d9ded7; border-radius: 8px; padding: 14px; box-shadow: 0 1px 2px rgba(23, 32, 38, 0.05); }
.card span { display: block; color: #667366; font-size: 12px; }
.card strong { display: block; margin-top: 6px; font-size: 16px; overflow-wrap: anywhere; }
.table-wrap { overflow-x: auto; }
table { width: 100%; border-collapse: collapse; min-width: 760px; }
th, td { text-align: left; border-bottom: 1px solid #e3e7df; padding: 9px; vertical-align: top; }
th { color: #435047; font-size: 12px; text-transform: uppercase; }
tr.pass td:first-child { color: #047857; font-weight: 700; }
tr.warn td:first-child { color: #b45309; font-weight: 700; }
tr.fail td:first-child { color: #b91c1c; font-weight: 700; }
pre { white-space: pre-wrap; overflow-wrap: anywhere; background: #172026; color: #f7faf2; border-radius: 8px; padding: 12px; }
li { margin: 7px 0; }
footer { color: #69756a; font-size: 12px; }
</style>"""


def _card(label: str, value: Any) -> str:
    return f'<div class="card"><span>{_e(label)}</span><strong>{_e(value)}</strong></div>'


__all__ = [
    "render_training_scale_gate_html",
    "render_training_scale_gate_markdown",
    "write_training_scale_gate_csv",
    "write_training_scale_gate_html",
    "write_training_scale_gate_json",
    "write_training_scale_gate_markdown",
    "write_training_scale_gate_outputs",
]
