from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any


def write_training_portfolio_json(report: dict[str, Any], path: str | Path) -> None:
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")


def render_training_portfolio_markdown(report: dict[str, Any]) -> str:
    execution = _dict(report.get("execution"))
    lines = [
        f"# {report.get('title', 'MiniGPT training portfolio pipeline')}",
        "",
        f"- Generated: `{report.get('generated_at')}`",
        f"- Project root: `{report.get('project_root')}`",
        f"- Status: `{execution.get('status')}`",
        f"- Dataset: `{report.get('dataset_name')}@{report.get('dataset_version')}`",
        f"- Run name: `{report.get('run_name')}`",
        "",
        "## Pipeline Steps",
        "",
        "| # | Key | Title | Command | Expected Outputs |",
        "| --- | --- | --- | --- | --- |",
    ]
    for index, step in enumerate(_list_of_dicts(report.get("steps")), start=1):
        lines.append(
            "| "
            + " | ".join(
                [
                    str(index),
                    _md(step.get("key")),
                    _md(step.get("title")),
                    _md(_display_command(step.get("command"))),
                    _md(", ".join(_string_list(step.get("expected_outputs")))),
                ]
            )
            + " |"
        )
    if _list_of_dicts(report.get("step_results")):
        lines.extend(["", "## Execution Results", "", "| Step | Return Code | Stdout Tail | Stderr Tail |", "| --- | --- | --- | --- |"])
        for result in _list_of_dicts(report.get("step_results")):
            lines.append(
                "| "
                + " | ".join(
                    [
                        _md(result.get("key")),
                        _md(result.get("returncode")),
                        _md(result.get("stdout_tail")),
                        _md(result.get("stderr_tail")),
                    ]
                )
                + " |"
            )
    lines.extend(["", "## Artifacts", "", "| Key | Exists | Path |", "| --- | --- | --- |"])
    for row in _list_of_dicts(report.get("artifact_rows")):
        lines.append(f"| {_md(row.get('key'))} | {_md(row.get('exists'))} | {_md(row.get('path'))} |")
    lines.extend(["", "## Recommendations", ""])
    lines.extend(f"- {item}" for item in _string_list(report.get("recommendations")))
    return "\n".join(lines).rstrip() + "\n"


def write_training_portfolio_markdown(report: dict[str, Any], path: str | Path) -> None:
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_training_portfolio_markdown(report), encoding="utf-8")


def render_training_portfolio_html(report: dict[str, Any]) -> str:
    execution = _dict(report.get("execution"))
    stats = [
        ("Status", execution.get("status")),
        ("Steps", execution.get("step_count")),
        ("Completed", execution.get("completed_steps")),
        ("Artifacts", f"{execution.get('available_artifact_count')}/{execution.get('artifact_count')}"),
        ("Dataset", f"{report.get('dataset_name')}@{report.get('dataset_version')}"),
        ("Run", report.get("run_name")),
    ]
    return "\n".join(
        [
            "<!doctype html>",
            '<html lang="zh-CN">',
            "<head>",
            '<meta charset="utf-8">',
            '<meta name="viewport" content="width=device-width, initial-scale=1">',
            '<link rel="icon" href="data:,">',
            f"<title>{_e(report.get('title', 'MiniGPT training portfolio pipeline'))}</title>",
            _style(),
            "</head>",
            "<body>",
            f"<header><h1>{_e(report.get('title', 'MiniGPT training portfolio pipeline'))}</h1><p>{_e(report.get('project_root'))}</p></header>",
            '<section class="stats">' + "".join(_card(label, value) for label, value in stats) + "</section>",
            _steps_section(_list_of_dicts(report.get("steps"))),
            _results_section(_list_of_dicts(report.get("step_results"))),
            _artifact_section(_list_of_dicts(report.get("artifact_rows"))),
            _list_section("Recommendations", report.get("recommendations")),
            "<footer>Generated by MiniGPT training portfolio pipeline.</footer>",
            "</body>",
            "</html>",
        ]
    )


def write_training_portfolio_html(report: dict[str, Any], path: str | Path) -> None:
    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_training_portfolio_html(report), encoding="utf-8")


def write_training_portfolio_outputs(report: dict[str, Any], out_dir: str | Path) -> dict[str, str]:
    root = Path(out_dir)
    root.mkdir(parents=True, exist_ok=True)
    paths = {
        "json": root / "training_portfolio.json",
        "markdown": root / "training_portfolio.md",
        "html": root / "training_portfolio.html",
    }
    write_training_portfolio_json(report, paths["json"])
    write_training_portfolio_markdown(report, paths["markdown"])
    write_training_portfolio_html(report, paths["html"])
    return {key: str(value) for key, value in paths.items()}


def _dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _list_of_dicts(value: Any) -> list[dict[str, Any]]:
    return [item for item in value if isinstance(item, dict)] if isinstance(value, list) else []


def _string_list(value: Any) -> list[str]:
    return [str(item) for item in value if str(item).strip()] if isinstance(value, list) else []


def _display_command(command: Any) -> str:
    parts = _string_list(command)
    return " ".join(_quote(part) for part in parts)


def _quote(value: str) -> str:
    if not value or any(ch.isspace() for ch in value):
        return '"' + value.replace('"', '\\"') + '"'
    return value


def _steps_section(steps: list[dict[str, Any]]) -> str:
    rows = "".join(
        "<tr>"
        f"<td>{index}</td>"
        f"<td>{_e(step.get('key'))}</td>"
        f"<td>{_e(step.get('title'))}</td>"
        f"<td><code>{_e(_display_command(step.get('command')))}</code></td>"
        f"<td>{_e(', '.join(_string_list(step.get('expected_outputs'))))}</td>"
        "</tr>"
        for index, step in enumerate(steps, start=1)
    )
    return (
        '<section class="panel"><h2>Pipeline Steps</h2>'
        '<table><thead><tr><th>#</th><th>Key</th><th>Title</th><th>Command</th><th>Expected Outputs</th></tr></thead><tbody>'
        + rows
        + "</tbody></table></section>"
    )


def _results_section(results: list[dict[str, Any]]) -> str:
    if not results:
        return '<section class="panel"><h2>Execution Results</h2><p class="muted">Dry run only. No steps executed.</p></section>'
    rows = "".join(
        "<tr>"
        f"<td>{_e(item.get('key'))}</td>"
        f"<td>{_e(item.get('returncode'))}</td>"
        f"<td>{_e(item.get('stdout_tail'))}</td>"
        f"<td>{_e(item.get('stderr_tail'))}</td>"
        "</tr>"
        for item in results
    )
    return (
        '<section class="panel"><h2>Execution Results</h2>'
        '<table><thead><tr><th>Step</th><th>Code</th><th>Stdout Tail</th><th>Stderr Tail</th></tr></thead><tbody>'
        + rows
        + "</tbody></table></section>"
    )


def _artifact_section(rows: list[dict[str, Any]]) -> str:
    body = "".join(
        "<tr>"
        f"<td>{_e(row.get('key'))}</td>"
        f"<td>{_e(row.get('exists'))}</td>"
        f"<td>{_e(row.get('path'))}</td>"
        "</tr>"
        for row in rows
    )
    return (
        '<section class="panel"><h2>Artifacts</h2>'
        '<table><thead><tr><th>Key</th><th>Exists</th><th>Path</th></tr></thead><tbody>'
        + body
        + "</tbody></table></section>"
    )


def _list_section(title: str, values: Any) -> str:
    items = _string_list(values)
    if not items:
        return ""
    return f'<section class="panel"><h2>{_e(title)}</h2><ul>' + "".join(f"<li>{_e(item)}</li>" for item in items) + "</ul></section>"


def _card(label: str, value: Any) -> str:
    return (
        '<div class="card">'
        f'<div class="label">{_e(label)}</div>'
        f'<div class="value">{_e("missing" if value is None else value)}</div>'
        "</div>"
    )


def _style() -> str:
    return """<style>
:root { --ink:#172033; --muted:#596579; --line:#d9dfd2; --page:#f7f8f3; --panel:#fff; --green:#047857; --amber:#b45309; --blue:#1f5f74; }
* { box-sizing:border-box; }
body { margin:0; background:var(--page); color:var(--ink); font-family:Arial, "Microsoft YaHei", sans-serif; line-height:1.45; }
header { padding:28px 32px 18px; background:#fff; border-bottom:1px solid var(--line); }
h1 { margin:0 0 8px; font-size:28px; letter-spacing:0; }
h2 { margin:0 0 12px; font-size:18px; }
.muted, p, span { color:var(--muted); }
.stats { display:grid; grid-template-columns:repeat(auto-fit, minmax(170px, 1fr)); gap:12px; padding:18px 32px 4px; }
.card, .panel { background:var(--panel); border:1px solid var(--line); border-radius:8px; }
.card { padding:14px; min-height:84px; }
.label { color:var(--muted); font-size:12px; text-transform:uppercase; }
.value { margin-top:6px; font-size:19px; font-weight:700; overflow-wrap:anywhere; }
.panel { margin:18px 32px; padding:16px; overflow-x:auto; }
table { width:100%; border-collapse:collapse; min-width:980px; }
th, td { padding:9px 8px; border-bottom:1px solid var(--line); text-align:left; vertical-align:top; }
th { color:var(--muted); font-size:12px; text-transform:uppercase; }
code { white-space:normal; overflow-wrap:anywhere; color:var(--blue); }
ul { margin:0; padding-left:22px; }
li { margin:8px 0; }
footer { padding:20px 32px 34px; color:var(--muted); font-size:13px; }
@media (max-width:760px) { header, .stats { padding-left:16px; padding-right:16px; } .panel { margin-left:16px; margin-right:16px; } }
</style>"""


def _md(value: Any) -> str:
    text = "" if value is None else str(value)
    return text.replace("|", "\\|").replace("\n", " ")


def _e(value: Any) -> str:
    return html.escape("" if value is None else str(value), quote=True)
